### PR TITLE
fix: install toolchain version

### PR DESCRIPTION
**Pull request by erikburt**
### Changes

- Install the go version specified by the `toolchain` directive if it exists.

### Motivation

This is the cause for the errors seen during go mod cache restores for all of our workflows.

Basically the `actions/setup-go` action doesn't install the provided toolchain version, so when executing a `go` command later, it fetches the toolchain version and adds the toolchain's modules to the go mod cache. When we go to restore the cache, it can't overwrite the modules which are already present.

Related: https://github.com/actions/setup-go/issues/424

---

RE-3325

### CODE REVIEW

**Review by chainchad — DISMISSED** [review]

**Comment by jmank88** [comment]
IMHO we need to find a way to work with the tooling, not against it. This is an important feature for reproducability, and disallowing it can suddenly become a problem that surprises us later.

**Comment by jmank88** [comment]
Can we install the correct version if we read the toolchain first?
```
~/chainlink$ go mod edit -json | jq -r ".Toolchain"
go1.23.4
```

**Comment by erikburt** [comment]
AFAICT there's not a great solution to this. Is it possible that we keep the go version in sync with the desired toolchain version, then remove the toolchain directive?

What's the benefit of having a different go and toolchain versions? I don't know if there's subtleties, but it seems unnecessary.

**Comment by erikburt** [comment]
As you suggested, here is a workaround that gets the toolchain version, and installs that instead. https://github.com/actions/setup-go/issues/457#issuecomment-2480536859

```
      - uses: actions/checkout@v4
      - id: toolchain
        run: echo "version=$(sed -ne '/^toolchain /s/^toolchain go//p' go.mod)" >> "$GITHUB_OUTPUT"
      - uses: actions/setup-go@v5
        with:
          go-version: ${{ steps.toolchain.outputs.version }}
```

**Review by AKhozya — APPROVED** [review]

**Review by jmank88 — APPROVED** [review]

**Pull request merged**
