### PR TITLE
renamed Buffer.sol to avoid conflicts in Truffle console

### LINKED ISSUE #3322: [SMRT] Buffer.sol conflicting with Node's Buffer object in Truffle console
**Description**
See: https://github.com/trufflesuite/truffle/issues/3329

Renaming [Buffer.sol](https://github.com/smartcontractkit/chainlink/blob/dd4c6d9eeb4ccc47d3973d7a8ebf6c79c38b155b/evm-contracts/src/v0.6/vendor/Buffer.sol) to something like BufferChainlink.sol (since it is imported as Buffer_Chainlink already anyway) is a workaround for this issue. The actual fix has to come from truffle.

### PR DESCRIPTION
**Pull request by mktcode**
fixes #3322

Untested. Please review and check. I also think the alias `BufferChainlink as Buffer_Chainlink` is not necessary but I left it to not be too invasive.

### CODE REVIEW

**Comment by se3000** [comment]
@mktcode Thanks for solving this. Small suggestion: do we still need the aliased import `as Buffer_Chainlink` if we've already namespaced the package? Seems like extra that we could cut out and simplify the whole package import naming. IIRC some flatteners don't handle the aliased imports very well, so this would be a nice opportunity to get rid of some.

**Comment by mktcode** [comment]
> I also think the alias BufferChainlink as Buffer_Chainlink is not necessary but I left it to not be too invasive.

I'll remove the aliases.

**Comment by se3000** [comment]
@mktcode what's the state of this?

**Comment by mktcode** [comment]
Noooooo I forgot.... gimme a sec. :D

**Comment by mktcode** [comment]
I'll do the same with CBOR.... even thogh it's not a native node object or so but still... just for the sake of consistency.

**Comment by se3000** [comment]
Thanks for fixing it up. It looks like you also need to rename CBOR to CBORChainlink in `evm-contracts/src/v0.6/vendor/CBORChainlink.sol`.

**Comment by mktcode** [comment]
Sorry, I have problems running tests. I pushed the lib renaming now but I will try to run the tests properly.

**Comment by se3000** [comment]
Thanks for raising this and seeing it through. I've reopened this branch as a PR so that it can get past some of the more tightly permissioned CI checks. Should have it merged shortly. https://github.com/smartcontractkit/chainlink/pull/3471

**Pull request closed without merging**
