### PR TITLE
update Fantom defaults: PriceMin = '0'

### PR DESCRIPTION
**Pull request by jmank88**

### CODE REVIEW

**Review by samsondav — DISMISSED** [review]

**Review by prashantkumar1982 — DISMISSED** [review]

**Comment by jmank88** [comment]
Todo:
- [ ] reconsider this now that bumping support was added

**Comment by HelloKashif** [comment]
@jmank88 can we do forward with this PR now please? The config testing indicated no issues with disabling the Bump threshold.

**Comment by jmank88** [comment]
I think it will probably just be closed now since bumping support was added in the other PR, so this is no longer correct

**Comment by HelloKashif** [comment]
@jmank88 do you mean via PR #11805 ? Shouldn't we still disable the bump for FTM based on @dimriou 's [comment here](https://github.com/smartcontractkit/chainlink/pull/11805#discussion_r1461877679) . Even though we won't see bumping errors on FTM it might still not include txs if the bumped price is not same as what their api suggested

**Pull request closed without merging**
