### PR TITLE
Apply "integration" build tag to VRF Integration tests.

### PR DESCRIPTION
**Pull request by vreff**
These tests fail locally with parallelism on. Per [this link](https://github.blog/changelog/2020-04-15-github-actions-sets-the-ci-environment-variable-to-true/), the CI enables the "CI" envar for its tests by default, so these tests can be restricted to CI only, unless the VRF_LOCAL_TESTING override is enabled.

### CODE REVIEW

**Comment by jmank88** [comment]
Would it be simpler to put this behind the existing `integration` build tag rather than introduce multiple new environment variables?

**Review by samsondav — DISMISSED** [review]

**Comment by vreff** [comment]
> Would it be simpler to put this behind the existing `integration` build tag rather than introduce multiple new environment variables?

"CI" envar is actually already being used in some testing helpers: https://github.com/smartcontractkit/chainlink/blob/chore/VRF-local-testing/.github/actions/split-tests/src/index.mts#L101

Is it still easy to run these tests locally with `//go:build integration` added i.e `go test`, or will we have to uncomment that line for quick local testing?

**Comment by jmank88** [comment]
https://github.com/smartcontractkit/chainlink/blob/fa1900ebda3f93037117f770dfe4b316318a4356/tools/bin/go_core_tests#L11

Build tags are controlled via a flag: `-tags integration`

**Comment by vreff** [comment]
Good to know, made the switch.

**Review by makramkd — APPROVED** [review]

**Comment by makramkd** [comment]
Neat build tag 😄

**Comment by makramkd** [comment]
Actually I don't think the test is being run anymore, I don't see the ocr2vrf/internal package showing up in the shards: https://github.com/smartcontractkit/chainlink/actions/runs/3714673001 @jmank88 is the build tag being used correctly in this PR?

**Comment by jmank88** [comment]
> Actually I don't think the test is being run anymore, I don't see the ocr2vrf/internal package showing up in the shards: https://github.com/smartcontractkit/chainlink/actions/runs/3714673001 @jmank88 is the build tag being used correctly in this PR?

It looks correct. Maybe something was lost in the conversion to shards?

**Pull request merged**
