### PR TITLE
Fix applying replay-from-block value to initiator log subscriptions

### PR DESCRIPTION
**Pull request by spooktheducks**

### CODE REVIEW

**Comment by spooktheducks** [comment]
Tests fixed

**Comment by thodges-gh** [comment]
Something is still broken in the logic of `-replay-from-block`. For example, I should be able to start my node, note the latest block that it received (block 1), then stop the node. At this point, I send a Runlog request on-chain (block 2), while the node is off. I then should be able to wait a bit, and start the node with `-replay-from-block 3` and the Runlog that I sent in block 2 should _not_ trigger a job run. However, currently it does based on this PR.

**Comment by thodges-gh** [comment]
Looks like we get warnings now each time the node is started (this is without using the new replay from block flag):
```
2019-11-14T01:44:11Z [WARN]  replay from block ~> %!s(int64=-1)                 services/subscription.go:50
2019-11-14T01:44:11Z [WARN]  next head ~> 6770192                               services/subscription.go:51
2019-11-14T01:44:11Z [INFO]  Listening for runlog from block #6770192 (0x674e10) services/subscription.go:137 address=[all] jobID=334c462b717f4981b18d527a0fcf1c28
2019-11-14T01:44:11Z [WARN]  replay from block ~> %!s(int64=-1)                 services/subscription.go:50
2019-11-14T01:44:11Z [WARN]  next head ~> 6770192                               services/subscription.go:51
2019-11-14T01:44:11Z [INFO]  Listening for runlog from block #6770192 (0x674e10) services/subscription.go:137 address=[all] jobID=c04bb12c67ae465ba50371b3f4a47225
```
Any way to suppress this?

**Comment by spooktheducks** [comment]
@thodges-gh That's only there temporarily for debugging.  I'll eliminate the log before closing the PR.

**Comment by thodges-gh** [comment]
@spooktheducks Sounds good! Then I can verify `-replay-from-block` works now.

**Pull request merged**
