### PR TITLE
use custom winfile scheme to handle windows logger file URLs

### PR DESCRIPTION
**Pull request by dimroc**
Incorporate fix for windows and file:/// URL incompatibility: https://github.com/uber-go/zap/issues/621

### CODE REVIEW

**Comment by dimroc** [comment]
@NavyAdmiral could you take a pass for code review and testing on windows?

**Comment by NavyAdmiral** [comment]
Can confirm the fix works. Made sure it was still not working on master and afterwards checked out this PR to see it work, attaching pic just in case:
image
🚢

**Comment by jleeh** [comment]
Can confirm this works for me as well 👍

**Comment by jleeh** [comment]
I get the same test failure as the PR locally on Windows:
```
=== RUN   TestClient_LogToDiskOptionDisablesAsExpected
=== PAUSE TestClient_LogToDiskOptionDisablesAsExpected
=== CONT  TestClient_LogToDiskOptionDisablesAsExpected
=== RUN   TestClient_LogToDiskOptionDisablesAsExpected/LogToDisk_=_false_=>_no_log_on_disk
=== RUN   TestClient_LogToDiskOptionDisablesAsExpected/LogToDisk_=_true_=>_log_on_disk_(positive_control)
--- FAIL: TestClient_LogToDiskOptionDisablesAsExpected (0.01s)
    --- FAIL: TestClient_LogToDiskOptionDisablesAsExpected/LogToDisk_=_false_=>_no_log_on_disk (0.00s)
        local_client_test.go:219: 
            	Error Trace:	local_client_test.go:219
            	Error:      	Not equal: 
            	            	expected: false
            	            	actual  : true
            	Test:       	TestClient_LogToDiskOptionDisablesAsExpected/LogToDisk_=_false_=>_no_log_on_disk


Expected :false
Actual   :true
 <Click to see difference>


    --- PASS: TestClient_LogToDiskOptionDisablesAsExpected/LogToDisk_=_true_=>_log_on_disk_(positive_control) (0.00s)
FAIL

Process finished with exit code 1
```

**Pull request merged**
