### PR TITLE
Re-enable job claim test

### PR DESCRIPTION
**Pull request by samsondav**
Removing gorm has fixed this.

### CODE REVIEW

**Review by jmank88 — APPROVED** [review]

**Comment by jmank88** [comment]
@cl-homu r+

**Review by pinebit — APPROVED** [review]

**Comment by cl-homu** [comment]
:pushpin: Commit 76c245618773fed9de2f2e159a1eeffdc1134ece has been approved by `jmank88`

**Comment by cl-homu** [comment]
:hourglass: Testing commit 76c245618773fed9de2f2e159a1eeffdc1134ece with merge e4e66e0c26b46608abeac23c89d273d76183cf38...

**Comment by cl-homu** [comment]
:sunny: Test successful - [checks-core](https://github.com/smartcontractkit/chainlink/runs/4227674375?check_suite_focus=true), [checks-lint](https://github.com/smartcontractkit/chainlink/runs/4227674622?check_suite_focus=true), [checks-npm](https://github.com/smartcontractkit/chainlink/runs/4227674540?check_suite_focus=true), [checks-operator](https://github.com/smartcontractkit/chainlink/runs/4227674352?check_suite_focus=true), [checks-prettier](https://github.com/smartcontractkit/chainlink/runs/4227674847?check_suite_focus=true), [checks-solidity](https://github.com/smartcontractkit/chainlink/runs/4227674715?check_suite_focus=true)
Approved by: jmank88
Pushing e4e66e0c26b46608abeac23c89d273d76183cf38 to develop...

**Pull request merged**
