### PR TITLE
Commit out of date yarn.lock file

### PR DESCRIPTION
**Pull request by rupurt**

### CODE REVIEW

**Comment by samsondav** [comment]
@rupurt  we may consider adding the --frozen-lockfile option to the CI script so that an out of date yarn.lock becomes an error.

**Comment by j16r** [comment]
Wouldn't that break the build every time a new package gets released?

**Comment by samsondav** [comment]
@j16r no, it just makes sure that it installs whatever version is in the lockfile, rather than silently updating it.

**Comment by se3000** [comment]
@samsondav looks like we already do that: https://github.com/smartcontractkit/chainlink/blob/chore/update-yarn-lock2/GNUmakefile#L52

**Comment by j16r** [comment]
@se3000 does that get used everywhere though? I get the sense the makefile has been slowly making it's way into `circleci` files and bash scripts and `package.json`s.

**Comment by rupurt** [comment]
#2333

**Pull request merged**
