### PR TITLE
BCF-3380 Rename ChainReader imports to ContractReader to match common

### PR DESCRIPTION
**Pull request by ilija42**
- [common PR](https://github.com/smartcontractkit/chainlink-common/pull/759)
- [feeds PR](https://github.com/smartcontractkit/chainlink-feeds/pull/79)
- [solana PR](https://github.com/smartcontractkit/chainlink-solana/pull/848)
- [starknet PR](https://github.com/smartcontractkit/chainlink-starknet/pull/520)
- [cosmos PR](https://github.com/smartcontractkit/chainlink-cosmos/pull/418)

### CODE REVIEW

**Comment by Farber98** [comment]
need to run `make generate` to fix go.md

**Review by Farber98 — COMMENTED** [review]
need to run `make generate` to pass `CI Core / Clean Go Tidy & Generate (pull_request)` and fix `go.md`

**Review by silaslenihan — APPROVED** [review]
LGTM other than CI failures

**Review by Farber98 — APPROVED** [review]
lgtm

**Pull request merged**
