### PR TITLE
Log broadcaster backfill from latest head from DB

### PR DESCRIPTION
**Pull request by PiotrTrzpil**
To make sure we don't skip any logs if the node is down for an extended time:

- The INITIAL backfill should always run from the last head stored in DB (if we have one).
- Subsequently (when adding subscribers while node is running), it should not, but use backfill depth instead (10 by default)

### CODE REVIEW

**Review by samsondav — APPROVED** [review]

**Review by samsondav — COMMENTED** [review]
Is it possible to have a test?

**Review by connorwstein — CHANGES_REQUESTED** [review]
Wait this function is called in the resubscribe loop - so then we just won't ever use BlockBackfillDepth because latestHeadInDb will always be !=nil ?

**Comment by PiotrTrzpil** [comment]
@connorwstein yes - latestHeadInDb in practice will never be nil (as it's setup before the start of LB) - actually it would be more clear to add a check elsewhere

Do you think BlockBackfillDepth should rather still be used in some way?

**Comment by PiotrTrzpil** [comment]
@samsondav yup, added a test

**Review by connorwstein — APPROVED** [review]

**Pull request merged**
