### PR TITLE
[TT-1128] remove evm client usages

### PR DESCRIPTION
**Pull request by Tofel**

### CODE REVIEW

**Review by lukaszcl — CHANGES_REQUESTED** [review]
@Tofel how about removing these? 

image

**Comment by Tofel** [comment]
> @Tofel how about removing these?

I would love to, but CCIP requires it :/ Maybe we could do something smart like them injecting a couple of optional functions, to the builder?

**Review by skudasov — CHANGES_REQUESTED** [review]
Can we lift the client up and decouple it from any environment? In this case from `docker` builder? If we need to move some functionality out too, like funding, that's okay - more readable in tests and align with our long term goal - explicit usage of clients, envs and actions in tests:
```
env := someStaticEnvFromValuesPreset()
client1 := NewClient()
client2 := NewClient()
complexAction1(client1, client2, whatever..)
complexAction2(env, client1, ...)
assert1(env, client1, ...)
```
@AnieeG since CCIP is using some parts, please check this PR!

**Comment by Tofel** [comment]
superseded by https://github.com/smartcontractkit/chainlink/pull/13568

**Pull request closed without merging**
