### PR TITLE
adding github readme action to remind PR creators to add documentation

### PR DESCRIPTION
**Pull request by patrickhuie19**

### CODE REVIEW

**Review by jmank88 — COMMENTED** [review]
LGTM but I wonder if we should consider combining with the changelog check, to reduce comment spam?

**Comment by patrickhuie19** [comment]
> LGTM but I wonder if we should consider combining with the changelog check, to reduce comment spam?

Ha! - great catch, as always. I did consider this, but ultimately went with two separate comments since I think it's helpful when reviewers can throw a thumbs up on an individual comment to prod the PR creator in the right direction.

**Comment by jmank88** [comment]
> edit: and FWIW, I think the biggest lever we can pull to get rid of comment spam is reduce the "temporarily deployed to integration" comments

Yeah IIUC we are not in control of those :shrug:

**Comment by patrickhuie19** [comment]
> > edit: and FWIW, I think the biggest lever we can pull to get rid of comment spam is reduce the "temporarily deployed to integration" comments
> 
> Yeah IIUC we are not in control of those 🤷

Spent a bit of time on this and came up empty handed as well - https://github.com/orgs/community/discussions/56507 🙏

**Review by jmank88 — APPROVED** [review]

**Pull request merged**
