### PR TITLE
Display account address in GUI

### PR DESCRIPTION
**Pull request by rupurt**
[Finishes #161645628]

screen shot 2018-11-15 at 1 21 14 pm

### CODE REVIEW

**Comment by thodges-gh** [comment]
Why was the story changed to display the account address on the Config page instead of the About page? To me, this is somewhat misleading, as the node operator cannot simply set a different value and change the address.

**Comment by rupurt** [comment]
@thodges-gh from what I can recall it was because the `About` page is statically generated at build time

**Comment by thodges-gh** [comment]
Does the About page need to _only_ contain statically built content? Does it make sense that it's misleading to put an entry on the Config page that's not a configurable value?

**Comment by rupurt** [comment]
@thodges-gh agreed that it's confusing. It was mentioned that the configuration is being redesigned so that it can be updated at run time. `About` doesn't need to be static, but would need to be changed to get the same behavior.

Thoughts @se3000

**Comment by se3000** [comment]
It looks like about and config are probably going to get merged into one page, so I think leaving it where it is should be fine.

**Pull request merged**
