### PR TITLE
fix error scope to avoid data race

### PR DESCRIPTION
**Pull request by krehermann**
[BCF-3275](https://smartcontract-it.atlassian.net/browse/BCF-3275)

data race due to wrongly scoped error

I realized that this very likely the root cause of MERC-5697, so I've enabled these tests again, too.

[BCF-3275]: https://smartcontract-it.atlassian.net/browse/BCF-3275?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
[BCF-3275]: https://smartcontract-it.atlassian.net/browse/BCF-3275?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

### CODE REVIEW

**Review by krehermann — COMMENTED** [review]
seen here https://github.com/smartcontractkit/chainlink/actions/runs/9604391758/job/26489787711?pr=13640

**Review by jmank88 — DISMISSED** [review]

**Comment by jmank88** [comment]
Did you check the other versions for the same problem?

**Comment by krehermann** [comment]
> Did you check the other versions for the same problem?

i did now :)

found one more and did a quick audit of `err =` and put tighter scope on a couple other places in abundance of caution

**Review by jmank88 — DISMISSED** [review]

**Review by jmank88 — APPROVED** [review]

**Review by cedric-cordenier — APPROVED** [review]

**Review by samsondav — APPROVED** [review]
Nice find! Surprised the linter didn't catch this

**Review by vyzaldysanchez — APPROVED** [review]

**Pull request merged**
