### PR TITLE
Upgrade to 16.8 and remove use-hooks

### PR DESCRIPTION
**Pull request by NavyAdmiral**
@rupurt this is in response to https://github.com/smartcontractkit/chainlink/pull/978
types were set to 16.8 and lockfile was 16.7; use-hooks is no longer needed either

### CODE REVIEW

**Comment by rupurt** [comment]
🍻 it looks like there's a few failing tests atm

**Comment by rupurt** [comment]
@NavyAdmiral I messed around with the PR locally and it seems like the problem is that `useEffect` is not getting executed in Jest. I tried out the [mock approach recommended in here](https://github.com/kentcdodds/react-testing-library/issues/215) but haven't been able to get it to work yet.

**Comment by NavyAdmiral** [comment]
Ive reae about it too and it useLayoutEffect was mentioned as a workaround. Simple replacement didnt work and I didnt get to try anything else out yet

**Comment by NavyAdmiral** [comment]
Support for this will be added to enzyme soon. Until then, there is no purpose to this PR.

**Pull request closed without merging**
