### PR TITLE
Logger Injection pt. 7

### PR DESCRIPTION
**Pull request by jmank88**
Story details: https://app.shortcut.com/chainlinklabs/story/18500

### CODE REVIEW

**Comment by samsondav** [comment]
@cl-homu r+

**Comment by cl-homu** [comment]
:pushpin: Commit 12d356fc91ff0572be433a1c3c66b1d96e62a6dc has been approved by `samsondav`

**Comment by cl-homu** [comment]
:hourglass: Testing commit 12d356fc91ff0572be433a1c3c66b1d96e62a6dc with merge c8a90c3b545ee100dcbdde110bc936bcc907c913...

**Comment by cl-homu** [comment]
:broken_heart: Test failed - [checks-core](https://github.com/smartcontractkit/chainlink/runs/4230697648?check_suite_focus=true)

**Comment by jmank88** [comment]
@cl-homu retry

**Comment by cl-homu** [comment]
:hourglass: Testing commit 12d356fc91ff0572be433a1c3c66b1d96e62a6dc with merge 39d6ef31b5b5ac55332597e16a70b603d5bb6496...

**Comment by cl-homu** [comment]
:broken_heart: Test failed - [checks-core](https://github.com/smartcontractkit/chainlink/runs/4230920026?check_suite_focus=true)

**Comment by cl-homu** [comment]
:hourglass: Testing commit 12d356fc91ff0572be433a1c3c66b1d96e62a6dc with merge cc81dc02c8f6bb02ebb2c04036c284e5ff72bade...

**Comment by cl-homu** [comment]
:broken_heart: Test failed - [checks-core](https://github.com/smartcontractkit/chainlink/runs/4231016439?check_suite_focus=true)

**Comment by cl-homu** [comment]
:hourglass: Testing commit 12d356fc91ff0572be433a1c3c66b1d96e62a6dc with merge 995e7311c3b39025b0a9bfb472705e7417e378ec...

**Comment by cl-homu** [comment]
:sunny: Test successful - [checks-core](https://github.com/smartcontractkit/chainlink/runs/4231189687?check_suite_focus=true), [checks-lint](https://github.com/smartcontractkit/chainlink/runs/4231189677?check_suite_focus=true), [checks-npm](https://github.com/smartcontractkit/chainlink/runs/4231189939?check_suite_focus=true), [checks-operator](https://github.com/smartcontractkit/chainlink/runs/4231189782?check_suite_focus=true), [checks-prettier](https://github.com/smartcontractkit/chainlink/runs/4231189936?check_suite_focus=true), [checks-solidity](https://github.com/smartcontractkit/chainlink/runs/4231189746?check_suite_focus=true)
Approved by: samsondav
Pushing 995e7311c3b39025b0a9bfb472705e7417e378ec to develop...

**Pull request merged**
