### PR TITLE
fix: changelog generation formatting RE-3152

### PR DESCRIPTION
**Pull request by erikburt**
### Changes

- Switch from `@changesets/changelog-github` to a local file which doesn't include users in the changelog generation
    - This applies to both the root .changesets, and the contracts/.changesets configs
- Updated `package.json`s to remove the unused dependency, and explicitly declare the pre-existing transitive dependency which is now referenced in the changelog generation code

### Testing

Tested locally, new format of changelog is like:

```
# Changelog Chainlink Core

## 2.19.0

### Minor Changes

- [#14898](https://github.com/smartcontractkit/chainlink/pull/14898) [`a417740`](https://github.com/smartcontractkit/chainlink/commit/a41774035961ce88be2fed7c6759758a7f00881d) - Bump to start the next version

...
```

---

RE-3152

> Since this is for NOPs and the names can be unprofessional and it adds unwanted noise, we’d like to remove the `thanks @ghusername` in the changesets generated changelogs.

### CODE REVIEW

**Comment by momentmaker** [comment]
nice! should we also do this for changeset in `contracts`?

**Comment by erikburt** [comment]
> nice! should we also do this for changeset in contracts?

@momentmaker, it's already included in this PR.

**Review by momentmaker — APPROVED** [review]

**Comment by momentmaker** [comment]
> > nice! should we also do this for changeset in contracts?
> 
> @momentmaker, it's already included in this PR.

ahh sorry - totally missed it

**Comment by pavel-raykov** [comment]
> ### Changes
> * Switch from `@changesets/changelog-github` to a local file which doesn't include users in the changelog generation
>   
>   * This applies to both the root .changesets, and the contracts/.changesets configs
> * Updated `package.json`s to remove the unused dependency, and explicitly declare the pre-existing transitive dependency which is now referenced in the changelog generation code
> 
> ### Testing
> Tested locally, new format of changelog is like:
> 
> ```
> # Changelog Chainlink Core
> 
> ## 2.19.0
> 
> ### Minor Changes
> 
> - [#14898](https://github.com/smartcontractkit/chainlink/pull/14898) [`a417740`](https://github.com/smartcontractkit/chainlink/commit/a41774035961ce88be2fed7c6759758a7f00881d) - Bump to start the next version
> 
> ...
> ```
> 
> RE-3152

Would it be possible to give an example of the changelog generation before and after this change?

Also, stupid question - could one just use '@changesets/changelog-github' and then do some filtering to remove usernames? (or is this as hard as forking the changelog)

**Comment by momentmaker** [comment]
i don't think you can config it and what's @erikburt created the custom formatter.
https://github.com/changesets/changesets/blob/7323704dff6e76f488370db384579b86c95c866f/packages/changelog-github/src/index.ts#L116

and the example he gave in the description is the after and you can see the current changelog to see how currently is.

**Comment by pavel-raykov** [comment]
> i don't think you can config it and what's @erikburt created the custom formatter. [changesets/changesets@`7323704`/packages/changelog-github/src/index.ts#L116](https://github.com/changesets/changesets/blob/7323704dff6e76f488370db384579b86c95c866f/packages/changelog-github/src/index.ts#L116)
> 
> and the example he gave in the description is the after and you can see the current changelog to see how currently is.

Thanks, and what is the purpose of hiding the usernames - is this some privacy issue?

**Comment by momentmaker** [comment]
don't think so but more so a request from the core team - probably because of annoyance of getting tagged

**Comment by pavel-raykov** [comment]
> don't think so but more so a request from the core team - probably because of annoyance of getting tagged

Ok, @erikburt could you please update the description with the motivation for this change. Thanks!

**Review by pavel-raykov — APPROVED** [review]

**Review by jmank88 — APPROVED** [review]

**Review by RensR — APPROVED** [review]

**Pull request merged**
