### PR TITLE
VRF V1: Add a log message on successful pipeline run

### PR DESCRIPTION
**Pull request by Nic0S**
When we run the pipeline to submit a fulfillment, do an info log.

### CODE REVIEW

**Review by pramodhs2 — APPROVED** [review]

**Comment by makramkd** [comment]
Can we also possibly add request ID as a field to the other "Log received" log?

**Comment by Nic0S** [comment]
At the point of the "Log received" we haven't parsed the log so it's a little tricky to add it without changing under what conditions it gets logged. I think since we're logging the DecodedLog, it should be included within an object instead of as a separate tag

**Comment by makramkd** [comment]
How about adding a log after we parse the request?

```golang
// in handleLog
req, err := lsn.coordinator.ParseRandomnessRequest(lb.RawLog())
// ...
lsn.l.With(
  "requestID", hex.EncodeToString(req.RequestID[:]),
  "requestJobID", hex.EncodeToString(req.JobID[:]),
  "keyHash", hex.EncodeToString(req.KeyHash[:]),
  "fee", req.Fee,
  "sender", req.Sender.Hex(),
).Info("Enqueuing randomness request")

// ... rest of code ...
```

**Comment by Nic0S** [comment]
Yeah good idea, done!

**Review by makramkd — APPROVED** [review]

**Review by pramodhs2 — APPROVED** [review]

**Pull request merged**
