### PR TITLE
Silence console in explorer tests

### PR DESCRIPTION
**Pull request by NavyAdmiral**
For [#165300808](https://www.pivotaltracker.com/story/show/165300808)

Thoughts about this approach? (verbose isn't necessary, but it helps displaying all subtests)

### CODE REVIEW

**Comment by dimroc** [comment]
@NavyAdmiral can you show a before and after of the output on success and failure? I can't really discern the new experience solely from seeing the new flags `--silent --verbose`.

One request was to:
> Could we copy the go behavior, which prints the console if the test fails, but don't print otherwise?

But do whatever is within reason, and not too costly. We're not here to rewrite `jest`.

**Comment by NavyAdmiral** [comment]
@dimroc The difference with `verbose` is the tree view
```
 PASS  src/__tests__/realtime.test.ts
  realtime
    ✓ create a job run for valid JSON (52ms)
    ✓ can create and update a job run and task runs (40ms)
    ✓ can create a task run with transactionHash and status (32ms)
    ✓ rejects malformed json events with code 422 (16ms)
    ✓ reject invalid authentication (15ms)

 PASS  src/__tests__/controllers/jobRuns.test.ts
  #index
    with no runs
      ✓ returns empty (26ms)
    with runs
      ✓ returns runs with chainlink node names (28ms)
  #show
    ✓ returns the job run with task runs (22ms)
    ✓ returns the job run with only public chainlink node information (20ms)
    ✓ returns a 404 (13ms)
    with out of order task runs
      ✓ returns ordered task runs (26ms)
```
vs `no verbose`
```
```
 PASS  src/__tests__/realtime.test.ts
 PASS  src/__tests__/controllers/jobRuns.test.ts
```

**Comment by NavyAdmiral** [comment]
Errors are displayed the same. With this PR
```
 FAIL  src/__tests__/realtime.test.ts
  realtime
    × create a job run for valid JSON (307ms)
    √ can create and update a job run and task runs (181ms)
    √ can create a task run with transactionHash and status (176ms)
    √ rejects malformed json events with code 422 (146ms)
    √ reject invalid authentication (144ms)

  ● realtime › create a job run for valid JSON

    expect(received).toEqual(expected)

    Expected value to equal:
      2
    Received:
      1

      78 | 
      79 |     const taskRunCount = await db.manager.count(TaskRun)
    > 80 |     expect(taskRunCount).toEqual(2)
         |                          ^
      81 |   })
      82 | 
      83 |   it('can create and update a job run and task runs', async () => {

      at Object.<anonymous> (src/__tests__/realtime.test.ts:80:26)
      at fulfilled (src/__tests__/realtime.test.ts:4:58)
```

Without this PR
```
● realtime › create a job run for valid JSON

    expect(received).toEqual(expected)

    Expected value to equal:
      2
    Received:
      1

      78 | 
      79 |     const taskRunCount = await db.manager.count(TaskRun)
    > 80 |     expect(taskRunCount).toEqual(2)
         |                          ^
      81 |   })
      82 | 
      83 |   it('can create and update a job run and task runs', async () => {

      at Object.<anonymous> (src/__tests__/realtime.test.ts:80:26)
      at fulfilled (src/__tests__/realtime.test.ts:4:58)
```

**Comment by NavyAdmiral** [comment]
@rupurt removed reporter in favor of `--silent` package.json scripts

**Comment by NavyAdmiral** [comment]
@rupurt also fixed the error, should be ready for a review

**Pull request merged**
