### PR TITLE
[merged] Remove builder from CI tests

### PR DESCRIPTION
**Pull request by jkongie**

### CODE REVIEW

**Review by archseer — APPROVED** [review]

**Review by archseer — APPROVED** [review]

**Comment by archseer** [comment]
@cl-homu r+

**Comment by cl-homu** [comment]
:pushpin: Commit 16303db39a20542d38100fcf3a080009aadbb599 has been approved by `archseer`

**Comment by cl-homu** [comment]
:hourglass: Testing commit 16303db39a20542d38100fcf3a080009aadbb599 with merge f5f0c97e5cae7cd79aa80fa602d8710de8e1e76b...

**Comment by cl-homu** [comment]
:sunny: Test successful - [checks-core](https://github.com/smartcontractkit/chainlink/runs/4148698283?check_suite_focus=true), [checks-lint](https://github.com/smartcontractkit/chainlink/runs/4148698210?check_suite_focus=true), [checks-npm](https://github.com/smartcontractkit/chainlink/runs/4148698352?check_suite_focus=true), [checks-operator](https://github.com/smartcontractkit/chainlink/runs/4148698346?check_suite_focus=true), [checks-prettier](https://github.com/smartcontractkit/chainlink/runs/4148698338?check_suite_focus=true), [checks-solidity](https://github.com/smartcontractkit/chainlink/runs/4148698305?check_suite_focus=true)
Approved by: archseer
Pushing f5f0c97e5cae7cd79aa80fa602d8710de8e1e76b to develop...

**Pull request closed without merging**
