### PR TITLE
remove flakey test: TestMailbox_EmptyReceivesWhenCapacityIsOne

### PR DESCRIPTION
**Pull request by PiotrTrzpil**

### CODE REVIEW

**Comment by samsondav** [comment]
@cl-homu r+

**Comment by cl-homu** [comment]
:pushpin: Commit 120fe6af9f576f5c2aa676cafa54ba40802ca042 has been approved by `samsondav`

**Comment by cl-homu** [comment]
:hourglass: Testing commit 120fe6af9f576f5c2aa676cafa54ba40802ca042 with merge 0ee42023dc58a7b354c0a93bfe5a4f931c2175e3...

**Comment by cl-homu** [comment]
:sunny: Test successful - [checks-core](https://github.com/smartcontractkit/chainlink/runs/4228001073?check_suite_focus=true), [checks-lint](https://github.com/smartcontractkit/chainlink/runs/4228000908?check_suite_focus=true), [checks-npm](https://github.com/smartcontractkit/chainlink/runs/4228001167?check_suite_focus=true), [checks-operator](https://github.com/smartcontractkit/chainlink/runs/4228001131?check_suite_focus=true), [checks-prettier](https://github.com/smartcontractkit/chainlink/runs/4228001121?check_suite_focus=true), [checks-solidity](https://github.com/smartcontractkit/chainlink/runs/4228000905?check_suite_focus=true)
Approved by: samsondav
Pushing 0ee42023dc58a7b354c0a93bfe5a4f931c2175e3 to develop...

**Pull request merged**
