### PR TITLE
Add lock around txdb stmt close

### PR DESCRIPTION
**Pull request by samsondav**

### CODE REVIEW

**Review by jmank88 — APPROVED** [review]

**Comment by jmank88** [comment]
@cl-homu r+

**Comment by cl-homu** [comment]
:pushpin: Commit 1f199dd6c34cc7f5d3c1ae1315f2aa206552dd2a has been approved by `jmank88`

**Comment by cl-homu** [comment]
:hourglass: Testing commit 1f199dd6c34cc7f5d3c1ae1315f2aa206552dd2a with merge b02254df6ecdb35f9a864fcbe2eea336cc3a1924...

**Comment by cl-homu** [comment]
:sunny: Test successful - [checks-core](https://github.com/smartcontractkit/chainlink/runs/4239947011?check_suite_focus=true), [checks-lint](https://github.com/smartcontractkit/chainlink/runs/4239946644?check_suite_focus=true), [checks-npm](https://github.com/smartcontractkit/chainlink/runs/4239947213?check_suite_focus=true), [checks-operator](https://github.com/smartcontractkit/chainlink/runs/4239946761?check_suite_focus=true), [checks-prettier](https://github.com/smartcontractkit/chainlink/runs/4239946891?check_suite_focus=true), [checks-solidity](https://github.com/smartcontractkit/chainlink/runs/4239946907?check_suite_focus=true)
Approved by: jmank88
Pushing b02254df6ecdb35f9a864fcbe2eea336cc3a1924 to develop...

**Pull request merged**
