### PR TITLE
Remove gorm.io/datatypes dependency

### PR DESCRIPTION
**Pull request by archseer**
We were only using a single JSON type and I'd feel much better if the rest of gorm wasn't transitively imported.

### CODE REVIEW

**Review by jmank88 — APPROVED** [review]

**Comment by archseer** [comment]
@cl-homu r+

**Comment by cl-homu** [comment]
:pushpin: Commit 3b2d079f454d7e2610a67a7fbe06b6640f876d80 has been approved by `archseer`

**Comment by cl-homu** [comment]
:hourglass: Testing commit 3b2d079f454d7e2610a67a7fbe06b6640f876d80 with merge 782ffbeb82239a4e24d4a809beb8e7dc43734469...

**Comment by cl-homu** [comment]
:sunny: Test successful - [checks-core](https://github.com/smartcontractkit/chainlink/runs/4219960433?check_suite_focus=true), [checks-lint](https://github.com/smartcontractkit/chainlink/runs/4219960590?check_suite_focus=true), [checks-npm](https://github.com/smartcontractkit/chainlink/runs/4219960628?check_suite_focus=true), [checks-operator](https://github.com/smartcontractkit/chainlink/runs/4219960455?check_suite_focus=true), [checks-prettier](https://github.com/smartcontractkit/chainlink/runs/4219960657?check_suite_focus=true), [checks-solidity](https://github.com/smartcontractkit/chainlink/runs/4219960687?check_suite_focus=true)
Approved by: archseer
Pushing 782ffbeb82239a4e24d4a809beb8e7dc43734469 to develop...

**Pull request merged**
