### PR TITLE
Introduce JSON constructor

### PR DESCRIPTION
**Pull request by felder-cl**
Add NewJSON(..) to convert JSON marshallable entities into the JSON type.

This replaces some uses of injecting values into hand crafted JSON strings.

### CODE REVIEW

**Comment by j16r** [comment]
It doesn't appear to be used anywhere?

**Comment by felder-cl** [comment]
There's a use case in the Flux Monitor, maybe other places.  Wanted to validate the idea before implementing it further.

**Comment by j16r** [comment]
Personally I'd like to get rid of the gjson library, so maybe this optimization has not occurred to me.

**Comment by felder-cl** [comment]
> Personally I'd like to get rid of the gjson library, so maybe this optimization has not occurred to me.

How come?  Might be good to make this a long term plan

**Comment by j16r** [comment]
I can't remember the full reasoning, but I think it was something like: the `gjson` library's API is pretty ugly, does lots of mutating in place, most of its methods can be done with other libraries we are already using and it introduces a bunch of new types that make it unergonomic.

The main usage of it is in the models.JSON#Add iirc, which serializes and deserializes to strings in a somewhat inefficient way, and in theory that shouldn't error, but it has error signatures all over it that make the job processing code more complex.

**Comment by felder-cl** [comment]
I've created a follow up story for the above comment.
https://www.pivotaltracker.com/n/projects/2129823

There is a couple of use cases in the Flux Monitor where this is used.  OK to merge?  The current code base requires object -> string -> JSON mapping's which can be a bit bizarre.

**Pull request closed without merging**
