### PR TITLE
Log link amount made per run

### PR DESCRIPTION
**Pull request by NavyAdmiral**
For [#163044551](https://www.pivotaltracker.com/story/show/163044551)

### CODE REVIEW

**Comment by rupurt** [comment]
@NavyAdmiral can you add a test for this?

**Comment by NavyAdmiral** [comment]
> @NavyAdmiral can you add a test for this?

I couldn't find existing test for `ForLogger` so I didn't add any. Do you suggest that I create a new `ForLogger` test that tests everything, or can you point me to the code that tests the function?

**Comment by rupurt** [comment]
I feel like if there are no tests for `ForLogger` we should add them.

**Comment by NavyAdmiral** [comment]
> I feel like if there are no tests for `ForLogger` we should add them.

I added test function, but it's a bit iffy since `ForLogger` operates on a kvs slice interface and not a struct, so with my limited go knowledge i had to test using indices. How do you feel about it?

**Pull request merged**
