### PR TITLE
ORM: Ensure correct error types are returned

### PR DESCRIPTION
**Pull request by felder-cl**
The new orm.ErrorConflict was introduced recently to act as a table
signal to callers when conflicts occur, such as record already existing.
It was implemented only within the orm.CreateBridgeType(..) method.

To make the ORM entity more consistent, ensure support for returning
this error is added to all ORM's public methods.

### CODE REVIEW

**Comment by felder-cl** [comment]
> I don't believe we are expecting conflict errors in many of these cases, and neither is the caller, so I'm not sure this is going to have much of a benefit.

Its just for consistency.  A blanket policy may be easier to implement and more reliable than one where we guess where the error could be caught and transformed.  It also makes it practical to add on to if we want to introduce other similar errors to ErrorConflict.

Anything that could change your mind?

**Comment by j16r** [comment]
If we could do this in a more central place, rather than having to add it to every ORM method, than I'd be more partial to it. Right now you're making a change to nearly every ORM method and I'd expect a test case for all of them at the very least.

I'm not sure I'm going to do a good job at articulating this next point - but I feel like this also changes the nature of the code at runtime, rather than at compile time, which means that we're paying for more code to be executed in all these new cases, where in theory the new branches should never actually be reached. That doesn't feel right to me.

**Comment by felder-cl** [comment]
> I'm not sure I'm going to do a good job at articulating this next point - but I feel like this also changes the nature of the code at runtime, rather than at compile time, which means that we're paying for more code to be executed in all these new cases, where in theory the new branches should never actually be reached. That doesn't feel right to me.

Lets meet half way, and do it only where conflicts may crop up?

**Comment by se3000** [comment]
I agree that this seems a bit error prone. Ideally, you wouldn't have to remember to wrap the error every time. The first thing that comes to mind is to wrap the orm object so that it's `Error` has always already been mapped. Seems like a lot of work, but I already don't like that you have to go out of your way to check the `Error` attribute, it seems very un-Golang-like. Open to other ideas, but my inclination is if we go this route we'll quickly forget and end up with inconsistencies.

**Comment by felder-cl** [comment]
If consistency is preferred, what do you think about never calling '.Error(..)' and using an internal function to get it? Doing it this way would make it clear to readers of the code to use 'error(db)' instead of (db.Error).

Wrapping the entity wouldn't be too hard I believe, just very verbose.

**Comment by se3000** [comment]
Another idea: if we wrap it, could we change the methods that we're wrapping to just return an (already mapped) error and force people to check if it exists?

I'm afraid casing is kind of subtle, could be missed. Defaulting to returning errors, on the other hand, seems like idiomatic Go.

**Comment by felder-cl** [comment]
> Another idea: if we wrap it, could we change the methods that we're wrapping to just return an (already mapped) error and force people to check if it exists?
> 
> I'm afraid casing is kind of subtle, could be missed. Defaulting to returning errors, on the other hand, seems like idiomatic Go.

Do you mean on the DB entity itself?  I believe you mentioned this earlier.  It sounds like a good way to handle it.

**Comment by felder-cl** [comment]
Follow up story can be found at https://www.pivotaltracker.com/story/show/171207315

**Pull request closed without merging**
