### PR TITLE
Upgrade jest to 25.1.1

### PR DESCRIPTION
**Pull request by HenryNguyen5**
- TODO update new package in #2236 after its merged

### CODE REVIEW

**Comment by rupurt** [comment]
@HenryNguyen5 needs a rebase to resolve `yarn.lock` conflicts

**Comment by HenryNguyen5** [comment]
@rupurt got it, will do after #2236 is merged in

**Comment by rupurt** [comment]
Probably needs it here also https://github.com/smartcontractkit/chainlink/blob/develop/feeds/package.json#L62

**Comment by HenryNguyen5** [comment]
Closing due to CRA preflight check disallowing jest v25. Adding the check would mean un-ignoring their .env files which may be dangerous.

**Pull request closed without merging**
