### PR TITLE
GoLinter Changes and Comments

### PR DESCRIPTION
**Pull request by cholladay0816**
I want to start contributing to the Chainlink project and I'm using this PR to get started by making harmless improvements (fixing go-lint warnings, adding comments).

### CODE REVIEW

**Comment by samsondav** [comment]
@cholladay0816 looks good mate, let us know when you need a review

**Comment by cholladay0816** [comment]
> @cholladay0816 looks good mate, let us know when you need a review

Thank you, I'll submit it for review soon.  Also, I'm looking to get CircleCI to pass, is there anything I need to do?

**Comment by se3000** [comment]
@cholladay0816 CircleCI only runs for builds from branches of this repo. Once your PR branch has gone finished review, we'll push it up as a branch here and Circle should run. It's suboptimal, but we have to keep it locked down for security reasons. We're working on a better workflow long-term.

Thanks for the PR, looks great at a quick glance. Ping us when you're ready for review.

**Comment by cholladay0816** [comment]
@samsondav My PR is ready for review, thanks.

**Comment by connorwstein** [comment]
Merged in https://github.com/smartcontractkit/chainlink/pull/4193

**Pull request closed without merging**
