### PR TITLE
Remove gorm from feeds

### PR DESCRIPTION
**Pull request by samsondav**

### CODE REVIEW

**Review by jmank88 — APPROVED** [review]

**Comment by jmank88** [comment]
@cl-homu r+

**Comment by cl-homu** [comment]
:pushpin: Commit d277dea18ed77f1374fd6cc4f99ca4c99a360d8e has been approved by `jmank88`

**Comment by cl-homu** [comment]
:hourglass: Testing commit d277dea18ed77f1374fd6cc4f99ca4c99a360d8e with merge fc4f808c94e9439761f9fc70ff758435ad4715da...

**Comment by cl-homu** [comment]
:sunny: Test successful - [checks-core](https://github.com/smartcontractkit/chainlink/runs/4180090870?check_suite_focus=true), [checks-lint](https://github.com/smartcontractkit/chainlink/runs/4180091090?check_suite_focus=true), [checks-npm](https://github.com/smartcontractkit/chainlink/runs/4180091042?check_suite_focus=true), [checks-operator](https://github.com/smartcontractkit/chainlink/runs/4180090790?check_suite_focus=true), [checks-prettier](https://github.com/smartcontractkit/chainlink/runs/4180090907?check_suite_focus=true), [checks-solidity](https://github.com/smartcontractkit/chainlink/runs/4180090804?check_suite_focus=true)
Approved by: jmank88
Pushing fc4f808c94e9439761f9fc70ff758435ad4715da to develop...

**Pull request merged**
