### PR TITLE
Chore/upgrade builder to latest Rust SDK

### PR DESCRIPTION
**Pull request by samsondav**
Note: blocked by this issue

https://github.com/apache/incubator-teaclave-sgx-sdk/issues/209

### CODE REVIEW

**Comment by j16r** [comment]
The rust_test above works for me with the specified image - so I'm suspicious that 1.0.27 has been updated / diverged. Looking into it ...

**Comment by j16r** [comment]
Hmm that's not it:

```
smartcontract/builder              1.0.27              sha256:3acacdceee2557bcedea70e201248eb4b0bc109f1dc4b87de0a8ecb9f38b4849   f265f2438a4a        10 days ago         4.34GB
dockerhub: sha256:3acacdceee2557bcedea70e201248eb4b0bc109f1dc4b87de0a8ecb9f38b4849
```

**Comment by samsondav** [comment]
It compiles just fine. Only has the warning.

**Comment by j16r** [comment]
@samsondav I'm still seeing an error: https://circleci.com/gh/smartcontractkit/chainlink/121366?utm_campaign=vcs-integration-link&utm_medium=referral&utm_source=github-build-link

**Comment by samsondav** [comment]
@j16r Yeah, turns out I forgot to bump the image version in circle config. I think it will build OK now.

One point to note - I removed compiler-rt.

See: https://github.com/apache/incubator-teaclave-sgx-sdk/issues/209

I don’t know if that’s there because it was copypasta in the original Makefile, or if we decided we needed it for some reason. We can put this back and live with the warning if you prefer?

**Comment by j16r** [comment]
Yeah I had pushed commits to do all those things and it was still failing (looks like you force pushed over them).

**Comment by samsondav** [comment]
@j16r Ah dammit. Didnt know you were comitting to this also. Any way you can pull and merge so we can get your commits in too?

**Comment by j16r** [comment]
It's fine, your commits do the same thing.

**Pull request merged**
