### PR TITLE
core/chains/evm/log: replay set long query timeout

### PR DESCRIPTION
**Pull request by makramkd**
There are cases where a large amount of logs need to be marked as unconsumed, particularly for VRF replays that occur a while back. Using a longer query timeout in those cases would make sense because the alternative is deleting rows from the table (which requires infra assistance) in the event the MarkBroadcastsUnconsumed query times out.

### CODE REVIEW

**Comment by jmank88** [comment]
Is there some way to make this scale better? Seems like we should be looking for a longer term fix.

**Comment by makramkd** [comment]
Scale better in which way? As in replaying a specific range rather than replaying from a block to latest tip?

**Comment by jmank88** [comment]
> Scale better in which way? As in replaying a specific range rather than replaying from a block to latest tip?

I just mean the individual mark operations. Is there a fundamental issue with the table size growing? Or is it about the high concurrency during bursts (and timeout including e.g. waiting for a connection)? Both of those seem addressable.

**Comment by makramkd** [comment]
> I just mean the individual mark operations. Is there a fundamental issue with the table size growing? Or is it about the high concurrency during bursts (and timeout including e.g. waiting for a connection)? Both of those seem addressable.

I haven't measured it personally but I don't think that waiting for db connections is the issue (at least for VRF) since the DB footprint for VRF is very average if not below average (i.e log broadcaster writes to db, txm, and maybe the job pipeline stuff).

Table size in itself is not a fundamental issue since it depends on how many rows you're trying to mark as unconsumed - the replay request specifies a start block for the replay and do a bulk update to mark all rows in the log broadcasts table with block number >= that replay block number as unconsumed. So table size could be e.g 1M but if your replay range is only 1000 then I don't expect this query to take a long time.

We have an index on `(evm_chain_id, block_number)` in `log_broadcasts` and that index does get used in the update query in `MarkBroadcastsUnconsumed` so I don't suspect trimming the table down would help much for this.

**Review by jmank88 — APPROVED** [review]

**Review by jinhoonbang — APPROVED** [review]

**Pull request merged**
