### PR TITLE
Empty search query returns no results

### PR DESCRIPTION
**Pull request by rupurt**
[Finishes #165921655]

Screen Shot 2019-05-14 at 12 09 13 PM

### CODE REVIEW

**Comment by NavyAdmiral** [comment]
> [Finishes #165921655]
> 
> Screen Shot 2019-05-14 at 12 09 13 PM

What about setting min-height on empty state?

**Comment by rupurt** [comment]
@NavyAdmiral I like the min height idea for both. 

Screen Shot 2019-05-14 at 1 44 22 PM

**Comment by NavyAdmiral** [comment]
> @NavyAdmiral I like the min height idea for both.
> 
> Screen Shot 2019-05-14 at 1 44 22 PM

What's the rationale behind letting user submit an empty form? Shouldn't the input be required?

**Comment by rupurt** [comment]
@NavyAdmiral we removed the disabled buttons from the Operator UI so I'm assuming it's the same for the explorer.

Thoughts @thoughtmerchant

**Comment by NavyAdmiral** [comment]
@rupurt I'm also considering a red outline on the input if it's submitted while empty

**Pull request merged**
