### PR TITLE
Fix GNUmakefile

### PR DESCRIPTION
**Pull request by HenryNguyen5**
https://github.com/smartcontractkit/chainlink/pull/3625

### CODE REVIEW

**Review by se3000 — APPROVED** [review]

**Comment by willianpaixao** [comment]
Hi @HenryNguyen5,
I understand that you want to run the CI to ensure code quality, but closing my PR and opening another is a bummer for the original author.

CircleCI allows builds on PR from forks, instructions [here](https://circleci.com/blog/triggering-trusted-ci-jobs-on-untrusted-forks/).

**Comment by willianpaixao** [comment]
@HenryNguyen5  and for this PR, since Circle's build has passed, you could merge my original PR.

**Comment by se3000** [comment]
Hi @willianpaixao. First, thanks for your contribution. Henry's closing of your PR with a cross-reference for traceability is our standard action for outside contributors. We're working on smoothing out the process, but we just moved off of Circle because we found Github Actions gives us greater control. There are solutions for outside contributors like the one you linked to, but they are often just workarounds which skip builds which we actually need. We're actively working on improving CI and the workflow for outside contributors but that takes time, especially when juggling other priorities.

Henry has left your commit in-tact, I believe it is the same as a rebased commit. Our merge rules do not allow your original branch to be merged without the other CI builds passing, so we can't just merge the other branch without breaking much larger process and tooling setups. Thanks for the PR, and for your patience as we work towards a better process.

**Comment by willianpaixao** [comment]
@se3000 out of curiosity, how ChainLink has managed outside contribution so far? This processes would scare most developers. :(

Anyway, I'd be happy to help out on this improvements on workflow and process.

**Comment by se3000** [comment]
@willianpaixao it has been evolving over time with our needs, this was not always the case. We've tried to move towards automated processes for a lot of things, and optimize the main workflow and then improve the less common paths. If you could elaborate on what is scary about this workflow vs others, we're trying to improve it.

I should add the caveat that the PRs you touch happen to have a large overlap with the permissioned CI builds. Unit tests run fine, but infra around building and publishing is where credentials are required, causing the failing builds you've been seeing.

**Pull request merged**
