### PR TITLE
docker: Add hint in README

### PR DESCRIPTION
**Pull request by felder-cl**
Suggest way to clear up docker's storage space.

### CODE REVIEW

**Comment by jleeh** [comment]
Is this really needed? Did it stem from dev issues with the new compose setup?

**Comment by felder-cl** [comment]
It wasn't from issues from the dev setup, but I believe just from using docker over a period of time.  I eventually had an issue with several dozens of gigs taken up by docker after working with and re-building the environment.

Unsure if its needed, but thought it best to share this somewhere.

**Comment by jleeh** [comment]
I'd probably say it's best to re-work wiki pages like this and include an FAQ, rather than putting it in the main readme, seems a bit out of place:
https://github.com/smartcontractkit/chainlink/wiki/Development-Setup-Guide

**Comment by felder-cl** [comment]
Hmm, this is touching the docker's tools README file.  I'm unsure about the best place as I haven't gone much into the developer wiki yet.

**Pull request merged**
