### PR TITLE
core: embed unavailable gpg key

### PR DESCRIPTION
**Pull request by jmank88**

### CODE REVIEW

**Comment by chainchad** [comment]
While you're at it, want to update these too?

- core/chainlink.goreleaser.Dockerfile
- tools/docker/develop.Dockerfile (not sure if we use this?)

**Comment by chainchad** [comment]
@jmank88 moved it back to inline base64 in 968e24ffc5f9a2e8647190f15aeb8459f3820e44 like you had originally because I worry about how others use the Docker file in terms of relative paths.

**Review by chainchad — APPROVED** [review]

**Comment by chainchad** [comment]
Maybe this can be removed completely? See https://github.com/smartcontractkit/chainlink/pull/8572

**Comment by jmank88** [comment]
Closing in favor of #8572

**Pull request closed without merging**
