### PR TITLE
Removing gorm from service/job tests

### PR DESCRIPTION
**Pull request by pinebit**

### CODE REVIEW

**Review by samsondav — APPROVED** [review]
Now we are cooking on gas

**Comment by cl-homu** [comment]
:pushpin: Commit f00fb3322f6aa121ee39e5d8fa486e5c1e3fd7c0 has been approved by `samsondav`

**Comment by cl-homu** [comment]
:hourglass: Testing commit f00fb3322f6aa121ee39e5d8fa486e5c1e3fd7c0 with merge aa20d7752450a59c72b190b5f522a4e01cc4bbfa...

**Comment by cl-homu** [comment]
:sunny: Test successful - [checks-core](https://github.com/smartcontractkit/chainlink/runs/4212816605?check_suite_focus=true), [checks-lint](https://github.com/smartcontractkit/chainlink/runs/4212816538?check_suite_focus=true), [checks-npm](https://github.com/smartcontractkit/chainlink/runs/4212816832?check_suite_focus=true), [checks-operator](https://github.com/smartcontractkit/chainlink/runs/4212816851?check_suite_focus=true), [checks-prettier](https://github.com/smartcontractkit/chainlink/runs/4212816803?check_suite_focus=true), [checks-solidity](https://github.com/smartcontractkit/chainlink/runs/4212816528?check_suite_focus=true)
Approved by: samsondav
Pushing aa20d7752450a59c72b190b5f522a4e01cc4bbfa to develop...

**Pull request merged**
