### PR TITLE
feature: support arbitrum for ocr2vrf

### PR DESCRIPTION
**Pull request by makramkd**

### CODE REVIEW

**Comment by vreff** [comment]
Had originally left this comment on the contracts PR but it's better here: 

When we get a block from the log poller for Arbitrum, is the blockhash the correct L2 blockhash?

**Comment by makramkd** [comment]
> When we get a block from the log poller for Arbitrum, is the blockhash the correct L2 blockhash?

@vreff yes, it's the correct L2 blockhash and block number.

**Review by vreff — APPROVED** [review]

**Comment by vreff** [comment]
Approved, granted the implementation for the contracts don't change. If they do, this PR will obviously change.

**Comment by makramkd** [comment]
Closing, @jinhoonbang is doing it better in an upcoming PR.

**Pull request closed without merging**
