### PR TITLE
Unify timeout usage in tests

### PR DESCRIPTION
**Pull request by jmank88**
Story details: https://app.shortcut.com/chainlinklabs/story/16326

- Unify gomega default timeouts
- Remove unnecessary gomega helper (added in #5381)

### CODE REVIEW

**Review by pinebit — APPROVED** [review]

**Comment by jmank88** [comment]
@cl-homu r+

**Comment by cl-homu** [comment]
:pushpin: Commit f4e6623deea586b5289d064807be33af4e2af13c has been approved by `jmank88`

**Comment by cl-homu** [comment]
:hourglass: Testing commit f4e6623deea586b5289d064807be33af4e2af13c with merge aff8baf71c8c6a3e8ffbbcb086b194da939dc06d...

**Comment by cl-homu** [comment]
:broken_heart: Test failed - [checks-core](https://github.com/smartcontractkit/chainlink/runs/4178587204?check_suite_focus=true)

**Comment by jmank88** [comment]
@cl-homu retry
:tophat: :rabbit2:

**Comment by cl-homu** [comment]
:hourglass: Testing commit f4e6623deea586b5289d064807be33af4e2af13c with merge 9349fe55bbf41fcee6b541afb00b331b17da059a...

**Comment by cl-homu** [comment]
:broken_heart: Test failed - [checks-core](https://github.com/smartcontractkit/chainlink/runs/4178689529?check_suite_focus=true)

**Comment by jmank88** [comment]
@cl-homu retry
:mage_man:

**Comment by cl-homu** [comment]
:hourglass: Testing commit f4e6623deea586b5289d064807be33af4e2af13c with merge f02f1cdee20c08b4e3e37e3c3e32a5214ac74041...

**Comment by cl-homu** [comment]
:sunny: Test successful - [checks-core](https://github.com/smartcontractkit/chainlink/runs/4178817333?check_suite_focus=true), [checks-lint](https://github.com/smartcontractkit/chainlink/runs/4178817309?check_suite_focus=true), [checks-npm](https://github.com/smartcontractkit/chainlink/runs/4178817639?check_suite_focus=true), [checks-operator](https://github.com/smartcontractkit/chainlink/runs/4178817372?check_suite_focus=true), [checks-prettier](https://github.com/smartcontractkit/chainlink/runs/4178817640?check_suite_focus=true), [checks-solidity](https://github.com/smartcontractkit/chainlink/runs/4178817383?check_suite_focus=true)
Approved by: jmank88
Pushing f02f1cdee20c08b4e3e37e3c3e32a5214ac74041 to develop...

**Pull request merged**
