### PR TITLE
Backport 1.1/ci fix

### PR DESCRIPTION
**Pull request by jmank88**

### CODE REVIEW

**Review by samsondav — APPROVED** [review]

**Comment by samsondav** [comment]
@cl-homu r+

**Comment by cl-homu** [comment]
:pushpin: Commit 53fe4ff99e649948c3f9bcaab21acde754b1f82d has been approved by `samsondav`

**Comment by cl-homu** [comment]
:hourglass: Testing commit 53fe4ff99e649948c3f9bcaab21acde754b1f82d with merge cf11533462ee81317610f2bff5b84e85fbb0657e...

**Comment by cl-homu** [comment]
:broken_heart: Test failed - [checks-core](https://github.com/smartcontractkit/chainlink/runs/4216944018?check_suite_focus=true)

**Comment by jmank88** [comment]
@cl-homu r+

**Comment by cl-homu** [comment]
:bulb: This pull request was already approved, no need to approve it again.

- This pull request previously failed. You should add more commits to fix the bug, or use `retry` to trigger a build again.
- There's another pull request that is currently being tested, blocking this pull request: #5437

**Comment by cl-homu** [comment]
:pushpin: Commit 53fe4ff99e649948c3f9bcaab21acde754b1f82d has been approved by `jmank88`

**Comment by cl-homu** [comment]
:hourglass: Testing commit 53fe4ff99e649948c3f9bcaab21acde754b1f82d with merge 0ce9a567a4d82d4e4757dfbedf5d36a5c36f7b60...

**Comment by cl-homu** [comment]
:broken_heart: Test failed - [checks-core](https://github.com/smartcontractkit/chainlink/runs/4217117524?check_suite_focus=true)

**Comment by jmank88** [comment]
@cl-homu retry
:mage_man:

**Comment by cl-homu** [comment]
:hourglass: Testing commit 53fe4ff99e649948c3f9bcaab21acde754b1f82d with merge 210403e1f3a4c3ca4aec4b65a0cee405e1c1d8ba...

**Comment by cl-homu** [comment]
:broken_heart: Test failed - [checks-core](https://github.com/smartcontractkit/chainlink/runs/4217307573?check_suite_focus=true)

**Comment by jmank88** [comment]
@cl-homu retry
:fist_oncoming:

**Comment by cl-homu** [comment]
:hourglass: Testing commit 53fe4ff99e649948c3f9bcaab21acde754b1f82d with merge 1a1f1b251990c3b68cdbbea547800159580c186f...

**Comment by cl-homu** [comment]
:broken_heart: Test failed - [checks-core](https://github.com/smartcontractkit/chainlink/runs/4217396928?check_suite_focus=true)

**Comment by jmank88** [comment]
@cl-homu retry
:pleading_face:

**Comment by cl-homu** [comment]
:hourglass: Testing commit 53fe4ff99e649948c3f9bcaab21acde754b1f82d with merge dade6386954a2fc0bcea0e7e9778531884e7925b...

**Comment by cl-homu** [comment]
:broken_heart: Test failed - [checks-core](https://github.com/smartcontractkit/chainlink/runs/4217500966?check_suite_focus=true)

**Comment by jmank88** [comment]
@cl-homu retry
:moneybag:

**Comment by cl-homu** [comment]
:broken_heart: Test failed - [checks-core](https://github.com/smartcontractkit/chainlink/runs/4217637636?check_suite_focus=true)

**Comment by jmank88** [comment]
@cl-homu retry
:repeat:

**Comment by cl-homu** [comment]
:hourglass: Testing commit 53fe4ff99e649948c3f9bcaab21acde754b1f82d with merge 1b16c94979a11d4d5303c65cf1d6c919ac6060d4...

**Comment by cl-homu** [comment]
:broken_heart: Test failed - [checks-core](https://github.com/smartcontractkit/chainlink/runs/4217742246?check_suite_focus=true)

**Comment by jmank88** [comment]
@cl-homu retry
:infinity:

**Comment by cl-homu** [comment]
:hourglass: Testing commit 53fe4ff99e649948c3f9bcaab21acde754b1f82d with merge 8245ec78b722b712401535d9ace1f36db4618e54...

**Comment by cl-homu** [comment]
:broken_heart: Test failed - [checks-core](https://github.com/smartcontractkit/chainlink/runs/4217853001?check_suite_focus=true)

**Comment by jmank88** [comment]
@cl-homu retry
:confused:

**Comment by cl-homu** [comment]
:hourglass: Testing commit 53fe4ff99e649948c3f9bcaab21acde754b1f82d with merge a7917f8e2dbd12ae83d218ce3828c4497ecbcaee...

**Comment by cl-homu** [comment]
:broken_heart: Test failed - [checks-core](https://github.com/smartcontractkit/chainlink/runs/4218055090?check_suite_focus=true)

**Comment by jmank88** [comment]
@cl-homu retry
:hourglass_flowing_sand:

**Comment by cl-homu** [comment]
:hourglass: Testing commit 53fe4ff99e649948c3f9bcaab21acde754b1f82d with merge 6c8b75c7734d10e6314d1dc435c3d5174b31db31...

**Comment by cl-homu** [comment]
:broken_heart: Test failed - [checks-core](https://github.com/smartcontractkit/chainlink/runs/4218136983?check_suite_focus=true)

**Comment by jmank88** [comment]
@cl-homu retry
:man_shrugging:

**Comment by cl-homu** [comment]
:hourglass: Testing commit 53fe4ff99e649948c3f9bcaab21acde754b1f82d with merge 56dbd03a0e49e43bdc859a7b7261443941a7e91f...

**Comment by cl-homu** [comment]
:broken_heart: Test failed - [checks-core](https://github.com/smartcontractkit/chainlink/runs/4218218004?check_suite_focus=true)

**Comment by jmank88** [comment]
@cl-homu retry
:rocket:

**Comment by cl-homu** [comment]
:hourglass: Testing commit 53fe4ff99e649948c3f9bcaab21acde754b1f82d with merge 996d6907ef91870dae3d0cb1d9212846a8b58458...

**Comment by cl-homu** [comment]
:sunny: Test successful - [checks-core](https://github.com/smartcontractkit/chainlink/runs/4218785585?check_suite_focus=true), [checks-lint](https://github.com/smartcontractkit/chainlink/runs/4218785530?check_suite_focus=true), [checks-npm](https://github.com/smartcontractkit/chainlink/runs/4218785707?check_suite_focus=true), [checks-operator](https://github.com/smartcontractkit/chainlink/runs/4218785466?check_suite_focus=true), [checks-prettier](https://github.com/smartcontractkit/chainlink/runs/4218785678?check_suite_focus=true), [checks-solidity](https://github.com/smartcontractkit/chainlink/runs/4218785634?check_suite_focus=true)
Approved by: jmank88
Pushing 996d6907ef91870dae3d0cb1d9212846a8b58458 to release/1.1.0-rc0...

**Pull request merged**
