### PR TITLE
CFM-11.5 - Fix typo in core node

### PR DESCRIPTION
**Pull request by jkongie**
Story details: https://app.shortcut.com/chainlinklabs/story/21215

### CODE REVIEW

**Comment by jmank88** [comment]
@cl-homu r+

**Comment by cl-homu** [comment]
:pushpin: Commit 5f8319ce53a722dc787501d61817aeecc7d2fae8 has been approved by `jmank88`

**Comment by cl-homu** [comment]
:hourglass: Testing commit 5f8319ce53a722dc787501d61817aeecc7d2fae8 with merge e6a2e00e773fce2b0b73d28a602717c8f4286b97...

**Comment by cl-homu** [comment]
:broken_heart: Test failed - [checks-core](https://github.com/smartcontractkit/chainlink/runs/4189378309?check_suite_focus=true)

**Comment by jmank88** [comment]
@cl-homu retry
:business_suit_levitating:

**Comment by cl-homu** [comment]
:hourglass: Testing commit 5f8319ce53a722dc787501d61817aeecc7d2fae8 with merge a3d8581a6d4e92941db0a0e11891ef6d89f0eff1...

**Comment by cl-homu** [comment]
:sunny: Test successful - [checks-core](https://github.com/smartcontractkit/chainlink/runs/4189658634?check_suite_focus=true), [checks-lint](https://github.com/smartcontractkit/chainlink/runs/4189658560?check_suite_focus=true), [checks-npm](https://github.com/smartcontractkit/chainlink/runs/4189658444?check_suite_focus=true), [checks-operator](https://github.com/smartcontractkit/chainlink/runs/4189658537?check_suite_focus=true), [checks-prettier](https://github.com/smartcontractkit/chainlink/runs/4189658699?check_suite_focus=true), [checks-solidity](https://github.com/smartcontractkit/chainlink/runs/4189658338?check_suite_focus=true)
Approved by: jmank88
Pushing a3d8581a6d4e92941db0a0e11891ef6d89f0eff1 to develop...

**Pull request merged**
