### PR TITLE
Dependabot cascade

### PR DESCRIPTION
**Pull request by archseer**

### CODE REVIEW

**Review by jmank88 — APPROVED** [review]

**Comment by archseer** [comment]
@cl-homu r+

**Comment by cl-homu** [comment]
:pushpin: Commit bd691a19f3099a4019a4952d8467d86f4c01c19f has been approved by `archseer`

**Comment by cl-homu** [comment]
:hourglass: Testing commit bd691a19f3099a4019a4952d8467d86f4c01c19f with merge 2a3ca5e080e90d253f78e5a39ca4ff321a83ae52...

**Comment by cl-homu** [comment]
:sunny: Test successful - [checks-core](https://github.com/smartcontractkit/chainlink/runs/4100496243?check_suite_focus=true), [checks-lint](https://github.com/smartcontractkit/chainlink/runs/4100496265?check_suite_focus=true), [checks-npm](https://github.com/smartcontractkit/chainlink/runs/4100496307?check_suite_focus=true), [checks-operator](https://github.com/smartcontractkit/chainlink/runs/4100496164?check_suite_focus=true), [checks-prettier](https://github.com/smartcontractkit/chainlink/runs/4100496313?check_suite_focus=true), [checks-solidity](https://github.com/smartcontractkit/chainlink/runs/4100496278?check_suite_focus=true)
Approved by: archseer
Pushing 2a3ca5e080e90d253f78e5a39ca4ff321a83ae52 to develop...

**Comment by cl-homu** [comment]
:eyes: Test was successful, but fast-forwarding failed: 422 At least 1 approving review is required by reviewers with write access.

**Review by se3000 — APPROVED** [review]

**Comment by jmank88** [comment]
@cl-homu r+

**Comment by cl-homu** [comment]
:bulb: This pull request was already approved, no need to approve it again.

- This pull request previously failed. You should add more commits to fix the bug, or use `retry` to trigger a build again.

**Comment by cl-homu** [comment]
:pushpin: Commit bd691a19f3099a4019a4952d8467d86f4c01c19f has been approved by `jmank88`

**Comment by cl-homu** [comment]
:hourglass: Testing commit bd691a19f3099a4019a4952d8467d86f4c01c19f with merge bf98ba782df6a6e2e5d1466c0875a53c835a8c15...

**Comment by archseer** [comment]
@jmank88 It seems like it's seeing your approvals but Homu gets blocked merging to master because of branch rules (it's treating it as a regular user that doesn't have any approvals)

**Comment by cl-homu** [comment]
:sunny: Test successful - [checks-core](https://github.com/smartcontractkit/chainlink/runs/4100681246?check_suite_focus=true), [checks-lint](https://github.com/smartcontractkit/chainlink/runs/4100681163?check_suite_focus=true), [checks-npm](https://github.com/smartcontractkit/chainlink/runs/4100681109?check_suite_focus=true), [checks-operator](https://github.com/smartcontractkit/chainlink/runs/4100681181?check_suite_focus=true), [checks-prettier](https://github.com/smartcontractkit/chainlink/runs/4100681233?check_suite_focus=true), [checks-solidity](https://github.com/smartcontractkit/chainlink/runs/4100681088?check_suite_focus=true)
Approved by: jmank88
Pushing bf98ba782df6a6e2e5d1466c0875a53c835a8c15 to develop...

**Comment by cl-homu** [comment]
:eyes: Test was successful, but fast-forwarding failed: 422 At least 1 approving review is required by reviewers with write access.

**Pull request merged**
