### PR TITLE
chore: remove gorm from pipeline/orm_test

### PR DESCRIPTION
**Pull request by RensR**

### CODE REVIEW

**Review by pinebit — APPROVED** [review]

**Review by archseer — APPROVED** [review]

**Comment by archseer** [comment]
@cl-homu r+

**Comment by cl-homu** [comment]
:pushpin: Commit 96604c22d4ba640aec01192b72b623279607dec0 has been approved by `archseer`

**Comment by cl-homu** [comment]
:hourglass: Testing commit 96604c22d4ba640aec01192b72b623279607dec0 with merge 55c50e8c684fd4c8b5f8d726a3905c15262bf6f2...

**Comment by cl-homu** [comment]
:broken_heart: Test failed - [checks-core](https://github.com/smartcontractkit/chainlink/runs/4210424270?check_suite_focus=true)

**Comment by RensR** [comment]
@cl-homu retry

**Comment by cl-homu** [comment]
@RensR: :key: Insufficient privileges: not in try users

**Comment by samsondav** [comment]
@cl-homu r+

**Comment by cl-homu** [comment]
:bulb: This pull request was already approved, no need to approve it again.

- This pull request previously failed. You should add more commits to fix the bug, or use `retry` to trigger a build again.

**Comment by cl-homu** [comment]
:pushpin: Commit 96604c22d4ba640aec01192b72b623279607dec0 has been approved by `samsondav`

**Comment by samsondav** [comment]
@cl-homu retry

**Comment by cl-homu** [comment]
:hourglass: Testing commit 96604c22d4ba640aec01192b72b623279607dec0 with merge c6961da10a69f66a97b5e9dcef157fee292f0e7e...

**Comment by cl-homu** [comment]
:sunny: Test successful - [checks-core](https://github.com/smartcontractkit/chainlink/runs/4211482630?check_suite_focus=true), [checks-lint](https://github.com/smartcontractkit/chainlink/runs/4211482393?check_suite_focus=true), [checks-npm](https://github.com/smartcontractkit/chainlink/runs/4211482794?check_suite_focus=true), [checks-operator](https://github.com/smartcontractkit/chainlink/runs/4211482299?check_suite_focus=true), [checks-prettier](https://github.com/smartcontractkit/chainlink/runs/4211482735?check_suite_focus=true), [checks-solidity](https://github.com/smartcontractkit/chainlink/runs/4211482394?check_suite_focus=true)
Approved by: samsondav
Pushing c6961da10a69f66a97b5e9dcef157fee292f0e7e to develop...

**Pull request merged**
