### PR TITLE
Terminal reset using common stdin file descriptor between OS

### PR DESCRIPTION
**Pull request by jleeh**
Fixes building on Windows.

### CODE REVIEW

**Comment by jleeh** [comment]
With this and #108 failing due to codecov/patch, should I love at trying to cover those lines?

**Comment by dimroc** [comment]
Hi @jleeh, don't worry about coverage with this PR. But let's DRY up the `int(os.Stdin.Fd())` into a private variable with a description name just above the consuming method:

```golang
var osSafeStdin = int(os.Stdin.Fd()) // https://linktoexplanationorstackoverflow?
```

Let me know if that works for you.

**Comment by dimroc** [comment]
Also @jleeh, can you paste the call stack and error you get when running `syscall.Stdin`. Pretty amazing it doesn't work for windows.

**Comment by jleeh** [comment]
Cheers, updated the PR.

It doesn't build at all, the windows library has the Stdin var as a Handle object not an int:
```go
var (
	Stdin  = getStdHandle(STD_INPUT_HANDLE)
	Stdout = getStdHandle(STD_OUTPUT_HANDLE)
	Stderr = getStdHandle(STD_ERROR_HANDLE)
)

func getStdHandle(h int) (fd Handle) {
	r, _ := GetStdHandle(h)
	CloseOnExec(r)
	return r
}
```

For the change, I seen that on line 106 in the same file you're using the same fd for reading the password:
```go
bytePwd, err := terminal.ReadPassword(int(os.Stdin.Fd()))
```

The exe builds and runs fine now though!

node-exe

**Comment by dimroc** [comment]
@jleeh Did you perhaps forget to push your changes? PR seems the same.

**Comment by jleeh** [comment]
Sorry, commit not pushed 🤦‍♂️

**Comment by dimroc** [comment]
Can you remove the ‘var’ and use := so we’re consistent w the rest of the code base?

**Comment by jleeh** [comment]
Updated the PR.

**Pull request merged**
