### PR TITLE
core/web: reduce router log level from info to debug

### PR DESCRIPTION
**Pull request by jmank88**
Logging every web request at info level seems awfully noisy, and in practice I often have to filter these messages out to see past them.

### CODE REVIEW

**Review by vyzaldysanchez — APPROVED** [review]

**Comment by jmank88** [comment]
> Is this worth mentioning in the CHANGELOG? I wonder if some nops depend on this being `Info` level?

I'm on the fence since we don't have an API contract for logs and shouldn't encourage dependencies like this :shrug:

**Review by makramkd — APPROVED** [review]

**Comment by jmank88** [comment]
bors try

**Comment by jmank88** [comment]
bors try

**Comment by jmank88** [comment]
bors merge

**Comment by jmank88** [comment]
bors r=jkongie

**Comment by jmank88** [comment]
bors delegate+

**Pull request merged**
