### PR TITLE
exclude sourcegraph missing dependency

### PR DESCRIPTION
**Pull request by skudasov**

### CODE REVIEW

**Review by nolag — DISMISSED** [review]

**Review by jmank88 — CHANGES_REQUESTED** [review]
Let's find a way to fix this that doesn't pollute the go.mod files

**Comment by nolag** [comment]
> Let's find a way to fix this that doesn't pollute the go.mod files

Can this be non-blocking to the PR?  When this isn't merged, my Goland blows up.  This seems critical enough to the dev experience that checking in for now is ok.

**Review by erikburt — DISMISSED** [review]

**Comment by erikburt** [comment]
The problem comes from https://github.com/NethermindEth/juno, which we use 0.3.1 (released may 2023).

```
github.com/NethermindEth/juno@v0.3.1 github.com/sourcegraph/sourcegraph/lib@v0.0.0-20221216004406-749998a2ac74
```

This references the sourcegraph repository before it went private: https://github.com/sourcegraph/sourcegraph-public-snapshot
> Sourcegraph transitioned to a private monorepo. This repository, sourcegraph/sourcegraph-public-snapshot is a publicly available copy of the sourcegraph/sourcegraph repository as it was just before the migration.

**Comment by jmank88** [comment]
> > Let's find a way to fix this that doesn't pollute the go.mod files
> 
> Can this be non-blocking to the PR? When this isn't merged, my Goland blows up. This seems critical enough to the dev experience that checking in for now is ok.

Historically, "for now" means until I personally clean it up later. We must stop accumulating hasty hacks like this. This particular case does not even make sense in principle, because it only excludes a single specific version when the entire repo was removed.

**Comment by jmank88** [comment]
> The problem comes from [NethermindEth/juno](https://github.com/NethermindEth/juno), which we use 0.3.1 (released may 2023).
> 
> ```
> github.com/NethermindEth/juno@v0.3.1 github.com/sourcegraph/sourcegraph/lib@v0.0.0-20221216004406-749998a2ac74
> ```
> 
> This references the sourcegraph repository before it went private: [sourcegraph/sourcegraph-public-snapshot](https://github.com/sourcegraph/sourcegraph-public-snapshot)
> 
> > Sourcegraph transitioned to a private monorepo. This repository, sourcegraph/sourcegraph-public-snapshot is a publicly available copy of the sourcegraph/sourcegraph repository as it was just before the migration.

Using a `replace` to point to the new public repo would be a much cleaner hack than the `exclude`.

**Review by jmank88 — APPROVED** [review]

**Review by nolag — APPROVED** [review]

**Pull request merged**
