### PR TITLE
Adding ethuint256 task for encoding a bigInt as an EVM word byte array

### PR DESCRIPTION
**Pull request by AndrewInsignares**
Task came out of working with v2 pipeline and looking for a task to convert bigInt as an EVM word byte array

### CODE REVIEW

**Review by samsondav — CHANGES_REQUESTED** [review]
Hmm, what specific problem is this solving? I think we wanted to go with a more general approach to evm encodng.

**Comment by connorwstein** [comment]
> Hmm, what specific problem is this solving? I think we wanted to go with a more general approach to evm encodng.

+1 - I think we'd want a generic eth_encode task type and re-use the code from https://github.com/smartcontractkit/chainlink/blob/98751552abe8439aa5fe899853640558421581d3/core/adapters/eth_tx.go#L279. But depends on the exact problem this is needed for

**Comment by AndrewInsignares** [comment]
This was pulled out from the CronV2 branch as it ended up not being used in the cron v2 imp, initially used to convert an int to an EVM encoded value just write to a transaction

Definitely makes sense to expand this to be more generic, @samsondav , @connorwstein, idea would be support all solidity types as an input/output? also to take in multiple input params?

**Comment by connorwstein** [comment]
> This was pulled out from the CronV2 branch as it ended up not being used in the cron v2 imp, initially used to convert an int to an EVM encoded value just write to a transaction
> 
> Definitely makes sense to expand this to be more generic, @samsondav , @connorwstein, idea would be support all solidity types as an input/output? also to take in multiple input params?

If its not required yet, let's leave it alone for now. Hard to design without knowing the exact use case

**Comment by AndrewInsignares** [comment]
@connorwstein sounds good, figured id put it out there but makes sense to keep for when we have a direct use case ~

**Pull request closed without merging**
