### PR TITLE
[merged] Remove gorm from chains/evm

### PR DESCRIPTION
**Pull request by samsondav**

### CODE REVIEW

**Review by pinebit — APPROVED** [review]

**Comment by pinebit** [comment]
@cl-homu r+

**Comment by cl-homu** [comment]
@pinebit: :key: Insufficient privileges: Not in reviewers

**Comment by makramkd** [comment]
@cl-homu r+

**Comment by cl-homu** [comment]
:pushpin: Commit e0159175956d410381eb19bc6676dc905e8627a8 has been approved by `makramkd`

**Comment by samsondav** [comment]
@cl-homu r+

**Comment by cl-homu** [comment]
:bulb: This pull request was already approved, no need to approve it again.

- There's another pull request that is currently being tested, blocking this pull request: #5402

**Comment by cl-homu** [comment]
:pushpin: Commit e0159175956d410381eb19bc6676dc905e8627a8 has been approved by `samsondav`

**Comment by cl-homu** [comment]
:umbrella: The latest upstream changes (presumably 9e838ce7adb3d1aaf1f36fb54f4e761f2578c897) made this pull request unmergeable. Please [resolve the merge conflicts](https://rustc-dev-guide.rust-lang.org/git.html#rebasing-and-conflicts).

**Comment by samsondav** [comment]
@cl-homu r+

**Comment by cl-homu** [comment]
:pushpin: Commit 8b42f676a7ce678f1cfbfc5b5510b0357f107449 has been approved by `samsondav`

**Comment by cl-homu** [comment]
:hourglass: Testing commit 8b42f676a7ce678f1cfbfc5b5510b0357f107449 with merge 1b39e910a5a6bee13aac1770c5afaa3563e2a3f5...

**Comment by cl-homu** [comment]
:broken_heart: Test failed - [checks-core](https://github.com/smartcontractkit/chainlink/runs/4168268254?check_suite_focus=true)

**Comment by samsondav** [comment]
@cl-homu retry

**Comment by cl-homu** [comment]
:hourglass: Testing commit 8b42f676a7ce678f1cfbfc5b5510b0357f107449 with merge 9df7b263fb2533400b9e792b5900a7dac88a6d19...

**Comment by cl-homu** [comment]
:broken_heart: Test failed - [checks-core](https://github.com/smartcontractkit/chainlink/runs/4168389904?check_suite_focus=true)

**Comment by samsondav** [comment]
@cl-homu retry

**Comment by cl-homu** [comment]
:hourglass: Testing commit 8b42f676a7ce678f1cfbfc5b5510b0357f107449 with merge 695bb1506bc896be5304368180e305f98ae3bacd...

**Comment by samsondav** [comment]
@cl-homu r+

**Comment by cl-homu** [comment]
:pushpin: Commit f2af2999f314308d09f326c92dd6f90105763100 has been approved by `samsondav`

**Comment by cl-homu** [comment]
:hourglass: Testing commit f2af2999f314308d09f326c92dd6f90105763100 with merge 65a04dc6383585823b61a35369d3e9c489e4e4f6...

**Comment by cl-homu** [comment]
:broken_heart: Test failed - [checks-core](https://github.com/smartcontractkit/chainlink/runs/4168587914?check_suite_focus=true)

**Comment by samsondav** [comment]
@cl-homu retry

**Comment by cl-homu** [comment]
:hourglass: Testing commit f2af2999f314308d09f326c92dd6f90105763100 with merge 9fa4dda4fbe80d688db908f187712d7d6277fa50...

**Comment by cl-homu** [comment]
:sunny: Test successful - [checks-core](https://github.com/smartcontractkit/chainlink/runs/4168789818?check_suite_focus=true), [checks-lint](https://github.com/smartcontractkit/chainlink/runs/4168789621?check_suite_focus=true), [checks-npm](https://github.com/smartcontractkit/chainlink/runs/4168789942?check_suite_focus=true), [checks-operator](https://github.com/smartcontractkit/chainlink/runs/4168789635?check_suite_focus=true), [checks-prettier](https://github.com/smartcontractkit/chainlink/runs/4168789765?check_suite_focus=true), [checks-solidity](https://github.com/smartcontractkit/chainlink/runs/4168789807?check_suite_focus=true)
Approved by: samsondav
Pushing 9fa4dda4fbe80d688db908f187712d7d6277fa50 to develop...

**Pull request closed without merging**
