### PR TITLE
Create ChainlinkClient.sol v0.5.0

### PR DESCRIPTION
**Pull request by RyanRHall**
Addresses [#166108859](https://www.pivotaltracker.com/n/projects/2129823/stories/166108859)

Created new workspace, *chainlinkv0.5*, inside of evm directory

Run this command to view all 0.4.24 &rightarrow; 0.5.0 changes in contracts
```
git diff --no-index --diff-filter=M evm/contracts evm/v0.5/contracts
```

### CODE REVIEW

**Comment by thodges-gh** [comment]
- I wouldn't lock the requester to only 0.5.0. The benefit here is that they can use a compiler version greater than 0.5.0. It's up to them to lock to a specific pragma version within their project.
- This is okay if it's a temporary step, but it should be fairly easy to add the required keywords to the Buffer and CBOR contracts so that they remain compatible with existing 0.4.24 contracts as well as >=0.5.0 contracts, instead of needing to copy them into the directory.
- This also looks like a temporary step: duplicating the Oracle.sol contract to 0.5.0. This is probably where we're going to need to make a decision in the 0.4.24 directory to either add the Solidity 5 keywords and unlock the pragma version, or have two separate versions of the oracle contract. Or we could do the same thing as the LinkToken, and use the pre-compiled bytecode and ABI instead of having duplicate versions of that contract.

**Comment by RyanRHall** [comment]
@thodges-gh - thanks for the review.

* I noticed all the contracts in `/evm` are locked to `0.4.24` - just wanted to follow the same design pattern. Should all contracts in `/v0.5` be unlocked to `^0.5.0` or just the ChainlinkRequestInterface??
* You're right, Buffer and CBOR work perfectly well with `pragma solidity >0.4.18 <0.6.0` and a few tweaks. I can make a PR for that, which would clean up this PR also...
* The Oracle contract can't open the pragma to include 0.5 because of breaking changes to call & delegate call, but I'd be more than happy to explore your solution as implemented with the link token.

**Comment by se3000** [comment]
>     * I noticed all the contracts in `/evm` are locked to `0.4.24` - just wanted to follow the same design pattern. Should all contracts in `/v0.5` be unlocked to `^0.5.0` or just the ChainlinkRequestInterface??

Let's go with unlocked for now.

>     * You're right, Buffer and CBOR work perfectly well with `pragma solidity >0.4.18 <0.6.0` and a few tweaks. I can make a PR for that, which would clean up this PR also...

Can we include it in this PR?
 
>     * The Oracle contract can't open the pragma to include 0.5 because of breaking changes to call & delegate call, but I'd be more than happy to explore your solution as implemented with the link token.

This sounds like the biggest change, let's hold off for this PR.

**Comment by RyanRHall** [comment]
@se3000 for CBOR and Buffer, I'd have to make PRs to [solidity-cborutils](https://github.com/smartcontractkit/solidity-cborutils) and [buffer](https://github.com/ensdomains/buffer)

**Pull request merged**
