### PR TITLE
Upgrade goose back to upstream 3.4.1

### PR DESCRIPTION
**Pull request by samsondav**

### CODE REVIEW

**Comment by jkongie** [comment]
Do we still want to allow out of order migrations? If so, it is not a feature that is enabled by default 

```
Supports missing (out-of-order) migrations with the -allow-missing flag, or if using as a library supply the functional option goose.WithAllowMissing() to Up, UpTo or UpByOne.
```

**Comment by makramkd** [comment]
Yes, it seems like we need to pass in `goose.WithAllowMissing()` if we want to allow out of order migrations, though it doesn't seem to complain locally if we don't provide it.

**Comment by samsondav** [comment]
I think what we may want to do is leave out of order migrations disabled until we actually need them.

**Comment by makramkd** [comment]
After some discussion with Sam, I think that it's probably better we be stricter and disallow out of order migrations until we strictly need them. My concern with allowing out of order migrations is that it might silently break something without us knowing.

**Review by makramkd — APPROVED** [review]

**Pull request merged**
