### PR TITLE
Recover from potential panics in ReceiveLogRequest

### PR DESCRIPTION
**Pull request by samsondav**
AFAIK there is no way for this code to panic. However, in case it
does, I propose that it's mildly preferable to continue on to the next
log event rather than crashing the node.

One potential issue is that panics can be caused by factors out of our control, e.g. OOM etc. Is recovery code like this definitely appropriate?

https://www.pivotaltracker.com/story/show/171578483

### CODE REVIEW

**Comment by spooktheducks** [comment]
If a particular job run panics and fails to finish executing, is there any risk that it'll stay in the DB getting picked up over and over by the job runner?

**Comment by j16r** [comment]
@spooktheducks yes I think so, unless this somehow returns an error to the caller?

**Comment by j16r** [comment]
As discussed in slack, there is also the concern that if we lock any mutexes near this code and don't handle unlock in a defer, this could cause a deadlock.

**Comment by samsondav** [comment]
Seems like the consensus is to abondan this approach due to the risk of potential deadlock then?

**Comment by j16r** [comment]
My approach to this would have been to track the number of attempts to process a run/job etc. and give up on the Nth attempt.

I think recovering from a panic could be workable, just makes me nervous ;)

**Comment by spooktheducks** [comment]
I agree with @j16r -- we'll probably want this information to bubble up in such a way that it results in a `RunStatusErrored`, and having something like `maxRetries` on the JobRun table in the DB.  I'd be willing to see the scope of this story expand enough to accomplish the former, which would require changing the signature of `callback` from `func(eth.Log)` to `func(eth.Log) error`, as well as giving `InitiatorSubscription` access to `store.ORM`.

**Comment by samsondav** [comment]
How is that going to help with potentially leaving locks hanging around though?

**Comment by samsondav** [comment]
In light of the comments, I think a better approach would be to just ensure we don't do anything panickable in this part of the code i.e. implement a `safeslice` function and don't dereference anything without a nil check.

**Comment by samsondav** [comment]
closing in favour of https://www.pivotaltracker.com/story/show/171687056

**Pull request closed without merging**
