### PR TITLE
[merged] core/cmd: expand TestClient_RunNodeShowsEnv to include all

### PR DESCRIPTION
**Pull request by jmank88**
Expanding TestClient_RunNodeShowsEnv to cover the full set of vars.

### CODE REVIEW

**Review by vyzaldysanchez — APPROVED** [review]
LGTM, though I prefer the programmatic way of validating each possible env var in the logs.

**Comment by j16r** [comment]
@cl-homu r+

**Comment by cl-homu** [comment]
:pushpin: Commit 01a3165e765e891eebf3df2254791fc1c018fa0f has been approved by `j16r`

**Comment by cl-homu** [comment]
:hourglass: Testing commit 01a3165e765e891eebf3df2254791fc1c018fa0f with merge 8e5ebd0cb00439e4cfb57d35f1a20c742ca5306a...

**Comment by cl-homu** [comment]
:broken_heart: Test failed - [checks-core](https://github.com/smartcontractkit/chainlink/runs/4123721533?check_suite_focus=true)

**Comment by j16r** [comment]
@cl-homu retry

**Comment by j16r** [comment]
@cl-homu r+

**Comment by cl-homu** [comment]
:bulb: This pull request was already approved, no need to approve it again.

**Comment by cl-homu** [comment]
:pushpin: Commit 01a3165e765e891eebf3df2254791fc1c018fa0f has been approved by `j16r`

**Comment by j16r** [comment]
@cl-homu retry

**Comment by j16r** [comment]
@cl-homu r-

**Comment by j16r** [comment]
@cl-homu r+

**Comment by cl-homu** [comment]
:pushpin: Commit 01a3165e765e891eebf3df2254791fc1c018fa0f has been approved by `j16r`

**Comment by cl-homu** [comment]
:hourglass: Testing commit 01a3165e765e891eebf3df2254791fc1c018fa0f with merge 1c70753b716ab11fd132fcd986274b382bb23ce4...

**Comment by cl-homu** [comment]
:sunny: Test successful - [checks-core](https://github.com/smartcontractkit/chainlink/runs/4124146789?check_suite_focus=true), [checks-lint](https://github.com/smartcontractkit/chainlink/runs/4124146718?check_suite_focus=true), [checks-npm](https://github.com/smartcontractkit/chainlink/runs/4124146714?check_suite_focus=true), [checks-operator](https://github.com/smartcontractkit/chainlink/runs/4124146716?check_suite_focus=true), [checks-prettier](https://github.com/smartcontractkit/chainlink/runs/4124146794?check_suite_focus=true), [checks-solidity](https://github.com/smartcontractkit/chainlink/runs/4124146741?check_suite_focus=true)
Approved by: j16r
Pushing 1c70753b716ab11fd132fcd986274b382bb23ce4 to develop...

**Pull request closed without merging**
