### PR TITLE
Fix unauthorized error msg in Sign In

### PR DESCRIPTION
**Pull request by NavyAdmiral**
Just a quickfix. 
To reproduce fill bridge/spec from, wait out before you are unauthorized and click Create. Error message isn't shown. Pics for clarity:
Before:
image

After:
image

### CODE REVIEW

**Comment by NavyAdmiral** [comment]
@rupurt Server responses are different for wrong credentials/unauthorized error. Should I consider both responses and edit this PR?

**Comment by rupurt** [comment]
@NavyAdmiral I'm having trouble replicating this. Do you mind posting a series of screenshots with the context of local storage at each step?

e.g.

Screen Shot 2019-03-11 at 1 54 01 PM

**Comment by NavyAdmiral** [comment]
@rupurt what does your NOTIFY_ERROR look like?
image

**Comment by NavyAdmiral** [comment]
For clarity here's a gif where an ERROR is dispatched but no errors are displayed in the form 
image

**Comment by rupurt** [comment]
@NavyAdmiral gotcha. I can replicate the flow from the GIF. I can't replicate the before image of the red box with no content.

**Comment by NavyAdmiral** [comment]
I dont remembet how the empty red box got into the original post as I stopped seeing them now too. Anyway do you think something should be done for the unaccounted error?

**Comment by rupurt** [comment]
@NavyAdmiral we should fix it if we can replicate the steps.

Can you rebase & update the test when you get a chance? I will merge when CI passes.

**Comment by dimroc** [comment]
Hi all, just hopping into the conversation a little later to fix up this PR and noticed an inconsistency in the `error` structure depending on the action type, `RECEIVE_SIGNIN_FAIL` or `NOTIFY_ERROR`. I worry that just switching it from `detail` to `msg` will cause a regression of another bug. Details below.

I propose making it so that all error types populate one expect field for the view to display. Leaning towards `msg`. This places most of the work in the reducer.

@rupurt let me know if I'm missing something.

1__notifications_js____go_src_github_com_smartcontractkit_chainlink_gui_src_connectors_redux_reducers__-_VIM__vim_


1__SignIn_js____go_src_github_com_smartcontractkit_chainlink_gui_src_containers__-_VIM__vim_

**Comment by rupurt** [comment]
@dimroc +1 to keeping it consistent and don't mind using `msg` instead of `detail` across the board.

**Comment by dimroc** [comment]
@rupurt This PR does just that. Approve and merge at your leisure.

**Pull request merged**
