### PR TITLE
Validate URLs for bridge creation

### PR DESCRIPTION
**Pull request by NavyAdmiral**
For [#159897390](https://www.pivotaltracker.com/story/show/159897390)

### CODE REVIEW

**Comment by se3000** [comment]
@rupurt I don't know if these need to be unique, I think it's possible that they aren't. I think @boxhock may have already made the DSG adapter capable of performing different actions via different payloads. At the very least, we don't need to block the acceptance of this PR for that.

**Comment by NavyAdmiral** [comment]
@rupurt @se3000 How do I tell what exactly is failing in the noisy go-postgre go-sqlite tests? I'm sure some of the existing bridge tests do not create bridges with URLs, but is going through the _all_ `web` tests and scrolling through the tests the best way to fix them?

**Comment by rupurt** [comment]
@NavyAdmiral for golang tests I look for `--- FAIL`. There's so much output in this example I had to download it as a txt file. This is what I got.

Screen Shot 2019-07-23 at 7 28 53 AM

**Comment by NavyAdmiral** [comment]
@rupurt Ah thank you! I saw fails on the last 2 lines that didn't say anything and that deceived me into thinking the golang `Fails` were not helpful

**Comment by NavyAdmiral** [comment]
@rupurt Please take a look whenever :package:

**Pull request merged**
