### PR TITLE
Adds Non-Blocking Integration Tests to CI

### PR DESCRIPTION
**Pull request by kalverra**
## Adds `integration-tests` folder

image

Tests are run on major PRs to check that basic integrations are working correctly.

```yaml
name: Integration Tests
on: [pull_request]
```

At the moment, these are intended to be non-blocking, but in the future, we hope to make them a regular part of the CI pipeline process.

### CODE REVIEW

**Comment by cl-homu** [comment]
:umbrella: The latest upstream changes (presumably 08781b5273d096219a140fa27fd5e8e738bb2ef5) made this pull request unmergeable. Please [resolve the merge conflicts](https://rustc-dev-guide.rust-lang.org/git.html#rebasing-and-conflicts).

**Comment by cl-homu** [comment]
:umbrella: The latest upstream changes (presumably #5676) made this pull request unmergeable. Please [resolve the merge conflicts](https://rustc-dev-guide.rust-lang.org/git.html#rebasing-and-conflicts).

**Comment by cl-homu** [comment]
:umbrella: The latest upstream changes (presumably #5740) made this pull request unmergeable. Please [resolve the merge conflicts](https://rustc-dev-guide.rust-lang.org/git.html#rebasing-and-conflicts).

**Comment by cl-homu** [comment]
:umbrella: The latest upstream changes (presumably #5750) made this pull request unmergeable. Please [resolve the merge conflicts](https://rustc-dev-guide.rust-lang.org/git.html#rebasing-and-conflicts).

**Comment by cl-homu** [comment]
:umbrella: The latest upstream changes (presumably f20690e8ede0cfead9df7f808f56a14f26469aaa) made this pull request unmergeable. Please [resolve the merge conflicts](https://rustc-dev-guide.rust-lang.org/git.html#rebasing-and-conflicts).

**Review by samsondav — APPROVED** [review]

**Pull request merged**
