### PR TITLE
[merged] Implements `DeleteBridge` mutation

### PR DESCRIPTION
**Pull request by vyzaldysanchez**
Closes: https://app.shortcut.com/chainlinklabs/story/20880/implement-delete-bridge-gql-mutation

This aims to create a mutation that will allow the deletion of bridges by name.

### CODE REVIEW

**Review by jmank88 — APPROVED** [review]

**Comment by jmank88** [comment]
@cl-homu r+

**Comment by cl-homu** [comment]
:pushpin: Commit 48289d0322e62767ec623382793ad2e8b162cc0b has been approved by `jmank88`

**Comment by cl-homu** [comment]
:hourglass: Testing commit 48289d0322e62767ec623382793ad2e8b162cc0b with merge f67741ec133a2689221f998d33565107306806e2...

**Comment by cl-homu** [comment]
:sunny: Test successful - [checks-core](https://github.com/smartcontractkit/chainlink/runs/4143603485?check_suite_focus=true), [checks-lint](https://github.com/smartcontractkit/chainlink/runs/4143603196?check_suite_focus=true), [checks-npm](https://github.com/smartcontractkit/chainlink/runs/4143603145?check_suite_focus=true), [checks-operator](https://github.com/smartcontractkit/chainlink/runs/4143603167?check_suite_focus=true), [checks-prettier](https://github.com/smartcontractkit/chainlink/runs/4143603499?check_suite_focus=true), [checks-solidity](https://github.com/smartcontractkit/chainlink/runs/4143603790?check_suite_focus=true)
Approved by: jmank88
Pushing f67741ec133a2689221f998d33565107306806e2 to feature/sc-20876/nodes-gql-queries...

**Comment by cl-homu** [comment]
:sunny: Test successful - [checks-core](https://github.com/smartcontractkit/chainlink/runs/4143603485?check_suite_focus=true), [checks-lint](https://github.com/smartcontractkit/chainlink/runs/4143603196?check_suite_focus=true), [checks-npm](https://github.com/smartcontractkit/chainlink/runs/4143603145?check_suite_focus=true), [checks-operator](https://github.com/smartcontractkit/chainlink/runs/4143603167?check_suite_focus=true), [checks-prettier](https://github.com/smartcontractkit/chainlink/runs/4143714316?check_suite_focus=true), [checks-solidity](https://github.com/smartcontractkit/chainlink/runs/4143603790?check_suite_focus=true)
Approved by: jmank88
Pushing f67741ec133a2689221f998d33565107306806e2 to feature/sc-20876/nodes-gql-queries...

**Comment by cl-homu** [comment]
:sunny: Test successful - [checks-core](https://github.com/smartcontractkit/chainlink/runs/4143603485?check_suite_focus=true), [checks-lint](https://github.com/smartcontractkit/chainlink/runs/4143714230?check_suite_focus=true), [checks-npm](https://github.com/smartcontractkit/chainlink/runs/4143603145?check_suite_focus=true), [checks-operator](https://github.com/smartcontractkit/chainlink/runs/4143603167?check_suite_focus=true), [checks-prettier](https://github.com/smartcontractkit/chainlink/runs/4143714316?check_suite_focus=true), [checks-solidity](https://github.com/smartcontractkit/chainlink/runs/4143603790?check_suite_focus=true)
Approved by: jmank88
Pushing f67741ec133a2689221f998d33565107306806e2 to feature/sc-20876/nodes-gql-queries...

**Comment by cl-homu** [comment]
:sunny: Test successful - [checks-core](https://github.com/smartcontractkit/chainlink/runs/4143603485?check_suite_focus=true), [checks-lint](https://github.com/smartcontractkit/chainlink/runs/4143714230?check_suite_focus=true), [checks-npm](https://github.com/smartcontractkit/chainlink/runs/4143713992?check_suite_focus=true), [checks-operator](https://github.com/smartcontractkit/chainlink/runs/4143603167?check_suite_focus=true), [checks-prettier](https://github.com/smartcontractkit/chainlink/runs/4143714316?check_suite_focus=true), [checks-solidity](https://github.com/smartcontractkit/chainlink/runs/4143603790?check_suite_focus=true)
Approved by: jmank88
Pushing f67741ec133a2689221f998d33565107306806e2 to feature/sc-20876/nodes-gql-queries...

**Comment by cl-homu** [comment]
:sunny: Test successful - [checks-core](https://github.com/smartcontractkit/chainlink/runs/4143603485?check_suite_focus=true), [checks-lint](https://github.com/smartcontractkit/chainlink/runs/4143714230?check_suite_focus=true), [checks-npm](https://github.com/smartcontractkit/chainlink/runs/4143713992?check_suite_focus=true), [checks-operator](https://github.com/smartcontractkit/chainlink/runs/4143714222?check_suite_focus=true), [checks-prettier](https://github.com/smartcontractkit/chainlink/runs/4143714316?check_suite_focus=true), [checks-solidity](https://github.com/smartcontractkit/chainlink/runs/4143603790?check_suite_focus=true)
Approved by: jmank88
Pushing f67741ec133a2689221f998d33565107306806e2 to feature/sc-20876/nodes-gql-queries...

**Comment by cl-homu** [comment]
:sunny: Test successful - [checks-core](https://github.com/smartcontractkit/chainlink/runs/4143603485?check_suite_focus=true), [checks-lint](https://github.com/smartcontractkit/chainlink/runs/4143714230?check_suite_focus=true), [checks-npm](https://github.com/smartcontractkit/chainlink/runs/4143723212?check_suite_focus=true), [checks-operator](https://github.com/smartcontractkit/chainlink/runs/4143714222?check_suite_focus=true), [checks-prettier](https://github.com/smartcontractkit/chainlink/runs/4143714316?check_suite_focus=true), [checks-solidity](https://github.com/smartcontractkit/chainlink/runs/4143603790?check_suite_focus=true)
Approved by: jmank88
Pushing f67741ec133a2689221f998d33565107306806e2 to feature/sc-20876/nodes-gql-queries...

**Comment by cl-homu** [comment]
:sunny: Test successful - [checks-core](https://github.com/smartcontractkit/chainlink/runs/4143603485?check_suite_focus=true), [checks-lint](https://github.com/smartcontractkit/chainlink/runs/4143714230?check_suite_focus=true), [checks-npm](https://github.com/smartcontractkit/chainlink/runs/4143724172?check_suite_focus=true), [checks-operator](https://github.com/smartcontractkit/chainlink/runs/4143714222?check_suite_focus=true), [checks-prettier](https://github.com/smartcontractkit/chainlink/runs/4143714316?check_suite_focus=true), [checks-solidity](https://github.com/smartcontractkit/chainlink/runs/4143603790?check_suite_focus=true)
Approved by: jmank88
Pushing f67741ec133a2689221f998d33565107306806e2 to feature/sc-20876/nodes-gql-queries...

**Comment by cl-homu** [comment]
:sunny: Test successful - [checks-core](https://github.com/smartcontractkit/chainlink/runs/4143603485?check_suite_focus=true), [checks-lint](https://github.com/smartcontractkit/chainlink/runs/4143714230?check_suite_focus=true), [checks-npm](https://github.com/smartcontractkit/chainlink/runs/4143736545?check_suite_focus=true), [checks-operator](https://github.com/smartcontractkit/chainlink/runs/4143714222?check_suite_focus=true), [checks-prettier](https://github.com/smartcontractkit/chainlink/runs/4143714316?check_suite_focus=true), [checks-solidity](https://github.com/smartcontractkit/chainlink/runs/4143603790?check_suite_focus=true)
Approved by: jmank88
Pushing f67741ec133a2689221f998d33565107306806e2 to feature/sc-20876/nodes-gql-queries...

**Comment by cl-homu** [comment]
:sunny: Test successful - [checks-core](https://github.com/smartcontractkit/chainlink/runs/4143603485?check_suite_focus=true), [checks-lint](https://github.com/smartcontractkit/chainlink/runs/4143714230?check_suite_focus=true), [checks-npm](https://github.com/smartcontractkit/chainlink/runs/4143737742?check_suite_focus=true), [checks-operator](https://github.com/smartcontractkit/chainlink/runs/4143714222?check_suite_focus=true), [checks-prettier](https://github.com/smartcontractkit/chainlink/runs/4143714316?check_suite_focus=true), [checks-solidity](https://github.com/smartcontractkit/chainlink/runs/4143603790?check_suite_focus=true)
Approved by: jmank88
Pushing f67741ec133a2689221f998d33565107306806e2 to feature/sc-20876/nodes-gql-queries...

**Comment by cl-homu** [comment]
:sunny: Test successful - [checks-core](https://github.com/smartcontractkit/chainlink/runs/4143603485?check_suite_focus=true), [checks-lint](https://github.com/smartcontractkit/chainlink/runs/4143714230?check_suite_focus=true), [checks-npm](https://github.com/smartcontractkit/chainlink/runs/4143737742?check_suite_focus=true), [checks-operator](https://github.com/smartcontractkit/chainlink/runs/4143714222?check_suite_focus=true), [checks-prettier](https://github.com/smartcontractkit/chainlink/runs/4143714316?check_suite_focus=true), [checks-solidity](https://github.com/smartcontractkit/chainlink/runs/4143714314?check_suite_focus=true)
Approved by: jmank88
Pushing f67741ec133a2689221f998d33565107306806e2 to feature/sc-20876/nodes-gql-queries...

**Comment by cl-homu** [comment]
:sunny: Test successful - [checks-core](https://github.com/smartcontractkit/chainlink/runs/4143603485?check_suite_focus=true), [checks-lint](https://github.com/smartcontractkit/chainlink/runs/4143714230?check_suite_focus=true), [checks-npm](https://github.com/smartcontractkit/chainlink/runs/4143746310?check_suite_focus=true), [checks-operator](https://github.com/smartcontractkit/chainlink/runs/4143714222?check_suite_focus=true), [checks-prettier](https://github.com/smartcontractkit/chainlink/runs/4143714316?check_suite_focus=true), [checks-solidity](https://github.com/smartcontractkit/chainlink/runs/4143714314?check_suite_focus=true)
Approved by: jmank88
Pushing f67741ec133a2689221f998d33565107306806e2 to feature/sc-20876/nodes-gql-queries...

**Comment by cl-homu** [comment]
:sunny: Test successful - [checks-core](https://github.com/smartcontractkit/chainlink/runs/4143603485?check_suite_focus=true), [checks-lint](https://github.com/smartcontractkit/chainlink/runs/4143714230?check_suite_focus=true), [checks-npm](https://github.com/smartcontractkit/chainlink/runs/4143746438?check_suite_focus=true), [checks-operator](https://github.com/smartcontractkit/chainlink/runs/4143714222?check_suite_focus=true), [checks-prettier](https://github.com/smartcontractkit/chainlink/runs/4143714316?check_suite_focus=true), [checks-solidity](https://github.com/smartcontractkit/chainlink/runs/4143714314?check_suite_focus=true)
Approved by: jmank88
Pushing f67741ec133a2689221f998d33565107306806e2 to feature/sc-20876/nodes-gql-queries...

**Comment by cl-homu** [comment]
:sunny: Test successful - [checks-core](https://github.com/smartcontractkit/chainlink/runs/4143603485?check_suite_focus=true), [checks-lint](https://github.com/smartcontractkit/chainlink/runs/4143714230?check_suite_focus=true), [checks-npm](https://github.com/smartcontractkit/chainlink/runs/4143759184?check_suite_focus=true), [checks-operator](https://github.com/smartcontractkit/chainlink/runs/4143714222?check_suite_focus=true), [checks-prettier](https://github.com/smartcontractkit/chainlink/runs/4143714316?check_suite_focus=true), [checks-solidity](https://github.com/smartcontractkit/chainlink/runs/4143714314?check_suite_focus=true)
Approved by: jmank88
Pushing f67741ec133a2689221f998d33565107306806e2 to feature/sc-20876/nodes-gql-queries...

**Comment by cl-homu** [comment]
:sunny: Test successful - [checks-core](https://github.com/smartcontractkit/chainlink/runs/4143603485?check_suite_focus=true), [checks-lint](https://github.com/smartcontractkit/chainlink/runs/4143714230?check_suite_focus=true), [checks-npm](https://github.com/smartcontractkit/chainlink/runs/4143760532?check_suite_focus=true), [checks-operator](https://github.com/smartcontractkit/chainlink/runs/4143714222?check_suite_focus=true), [checks-prettier](https://github.com/smartcontractkit/chainlink/runs/4143714316?check_suite_focus=true), [checks-solidity](https://github.com/smartcontractkit/chainlink/runs/4143714314?check_suite_focus=true)
Approved by: jmank88
Pushing f67741ec133a2689221f998d33565107306806e2 to feature/sc-20876/nodes-gql-queries...

**Comment by cl-homu** [comment]
:sunny: Test successful - [checks-core](https://github.com/smartcontractkit/chainlink/runs/4143603485?check_suite_focus=true), [checks-lint](https://github.com/smartcontractkit/chainlink/runs/4143714230?check_suite_focus=true), [checks-npm](https://github.com/smartcontractkit/chainlink/runs/4143762287?check_suite_focus=true), [checks-operator](https://github.com/smartcontractkit/chainlink/runs/4143714222?check_suite_focus=true), [checks-prettier](https://github.com/smartcontractkit/chainlink/runs/4143714316?check_suite_focus=true), [checks-solidity](https://github.com/smartcontractkit/chainlink/runs/4143714314?check_suite_focus=true)
Approved by: jmank88
Pushing f67741ec133a2689221f998d33565107306806e2 to feature/sc-20876/nodes-gql-queries...

**Comment by cl-homu** [comment]
:sunny: Test successful - [checks-core](https://github.com/smartcontractkit/chainlink/runs/4143603485?check_suite_focus=true), [checks-lint](https://github.com/smartcontractkit/chainlink/runs/4143714230?check_suite_focus=true), [checks-npm](https://github.com/smartcontractkit/chainlink/runs/4143769506?check_suite_focus=true), [checks-operator](https://github.com/smartcontractkit/chainlink/runs/4143714222?check_suite_focus=true), [checks-prettier](https://github.com/smartcontractkit/chainlink/runs/4143714316?check_suite_focus=true), [checks-solidity](https://github.com/smartcontractkit/chainlink/runs/4143714314?check_suite_focus=true)
Approved by: jmank88
Pushing f67741ec133a2689221f998d33565107306806e2 to feature/sc-20876/nodes-gql-queries...

**Comment by cl-homu** [comment]
:sunny: Test successful - [checks-core](https://github.com/smartcontractkit/chainlink/runs/4143603485?check_suite_focus=true), [checks-lint](https://github.com/smartcontractkit/chainlink/runs/4143714230?check_suite_focus=true), [checks-npm](https://github.com/smartcontractkit/chainlink/runs/4143769698?check_suite_focus=true), [checks-operator](https://github.com/smartcontractkit/chainlink/runs/4143714222?check_suite_focus=true), [checks-prettier](https://github.com/smartcontractkit/chainlink/runs/4143714316?check_suite_focus=true), [checks-solidity](https://github.com/smartcontractkit/chainlink/runs/4143714314?check_suite_focus=true)
Approved by: jmank88
Pushing f67741ec133a2689221f998d33565107306806e2 to feature/sc-20876/nodes-gql-queries...

**Comment by cl-homu** [comment]
:sunny: Test successful - [checks-core](https://github.com/smartcontractkit/chainlink/runs/4143723081?check_suite_focus=true), [checks-lint](https://github.com/smartcontractkit/chainlink/runs/4143714230?check_suite_focus=true), [checks-npm](https://github.com/smartcontractkit/chainlink/runs/4143787273?check_suite_focus=true), [checks-operator](https://github.com/smartcontractkit/chainlink/runs/4143714222?check_suite_focus=true), [checks-prettier](https://github.com/smartcontractkit/chainlink/runs/4143714316?check_suite_focus=true), [checks-solidity](https://github.com/smartcontractkit/chainlink/runs/4143714314?check_suite_focus=true)
Approved by: jmank88
Pushing f67741ec133a2689221f998d33565107306806e2 to feature/sc-20876/nodes-gql-queries...

**Comment by cl-homu** [comment]
:sunny: Test successful - [checks-core](https://github.com/smartcontractkit/chainlink/runs/4143723081?check_suite_focus=true), [checks-lint](https://github.com/smartcontractkit/chainlink/runs/4143714230?check_suite_focus=true), [checks-npm](https://github.com/smartcontractkit/chainlink/runs/4143794040?check_suite_focus=true), [checks-operator](https://github.com/smartcontractkit/chainlink/runs/4143714222?check_suite_focus=true), [checks-prettier](https://github.com/smartcontractkit/chainlink/runs/4143714316?check_suite_focus=true), [checks-solidity](https://github.com/smartcontractkit/chainlink/runs/4143714314?check_suite_focus=true)
Approved by: jmank88
Pushing f67741ec133a2689221f998d33565107306806e2 to feature/sc-20876/nodes-gql-queries...

**Comment by cl-homu** [comment]
:sunny: Test successful - [checks-core](https://github.com/smartcontractkit/chainlink/runs/4143746352?check_suite_focus=true), [checks-lint](https://github.com/smartcontractkit/chainlink/runs/4143714230?check_suite_focus=true), [checks-npm](https://github.com/smartcontractkit/chainlink/runs/4143818286?check_suite_focus=true), [checks-operator](https://github.com/smartcontractkit/chainlink/runs/4143714222?check_suite_focus=true), [checks-prettier](https://github.com/smartcontractkit/chainlink/runs/4143714316?check_suite_focus=true), [checks-solidity](https://github.com/smartcontractkit/chainlink/runs/4143714314?check_suite_focus=true)
Approved by: jmank88
Pushing f67741ec133a2689221f998d33565107306806e2 to feature/sc-20876/nodes-gql-queries...

**Comment by cl-homu** [comment]
:sunny: Test successful - [checks-core](https://github.com/smartcontractkit/chainlink/runs/4143746352?check_suite_focus=true), [checks-lint](https://github.com/smartcontractkit/chainlink/runs/4143714230?check_suite_focus=true), [checks-npm](https://github.com/smartcontractkit/chainlink/runs/4143819920?check_suite_focus=true), [checks-operator](https://github.com/smartcontractkit/chainlink/runs/4143714222?check_suite_focus=true), [checks-prettier](https://github.com/smartcontractkit/chainlink/runs/4143714316?check_suite_focus=true), [checks-solidity](https://github.com/smartcontractkit/chainlink/runs/4143714314?check_suite_focus=true)
Approved by: jmank88
Pushing f67741ec133a2689221f998d33565107306806e2 to feature/sc-20876/nodes-gql-queries...

**Comment by cl-homu** [comment]
:sunny: Test successful - [checks-core](https://github.com/smartcontractkit/chainlink/runs/4143762175?check_suite_focus=true), [checks-lint](https://github.com/smartcontractkit/chainlink/runs/4143714230?check_suite_focus=true), [checks-npm](https://github.com/smartcontractkit/chainlink/runs/4143819920?check_suite_focus=true), [checks-operator](https://github.com/smartcontractkit/chainlink/runs/4143714222?check_suite_focus=true), [checks-prettier](https://github.com/smartcontractkit/chainlink/runs/4143714316?check_suite_focus=true), [checks-solidity](https://github.com/smartcontractkit/chainlink/runs/4143714314?check_suite_focus=true)
Approved by: jmank88
Pushing f67741ec133a2689221f998d33565107306806e2 to feature/sc-20876/nodes-gql-queries...

**Comment by cl-homu** [comment]
:sunny: Test successful - [checks-core](https://github.com/smartcontractkit/chainlink/runs/4143784898?check_suite_focus=true), [checks-lint](https://github.com/smartcontractkit/chainlink/runs/4143714230?check_suite_focus=true), [checks-npm](https://github.com/smartcontractkit/chainlink/runs/4143843296?check_suite_focus=true), [checks-operator](https://github.com/smartcontractkit/chainlink/runs/4143714222?check_suite_focus=true), [checks-prettier](https://github.com/smartcontractkit/chainlink/runs/4143714316?check_suite_focus=true), [checks-solidity](https://github.com/smartcontractkit/chainlink/runs/4143714314?check_suite_focus=true)
Approved by: jmank88
Pushing f67741ec133a2689221f998d33565107306806e2 to feature/sc-20876/nodes-gql-queries...

**Comment by cl-homu** [comment]
:sunny: Test successful - [checks-core](https://github.com/smartcontractkit/chainlink/runs/4143795551?check_suite_focus=true), [checks-lint](https://github.com/smartcontractkit/chainlink/runs/4143714230?check_suite_focus=true), [checks-npm](https://github.com/smartcontractkit/chainlink/runs/4143859834?check_suite_focus=true), [checks-operator](https://github.com/smartcontractkit/chainlink/runs/4143714222?check_suite_focus=true), [checks-prettier](https://github.com/smartcontractkit/chainlink/runs/4143714316?check_suite_focus=true), [checks-solidity](https://github.com/smartcontractkit/chainlink/runs/4143714314?check_suite_focus=true)
Approved by: jmank88
Pushing f67741ec133a2689221f998d33565107306806e2 to feature/sc-20876/nodes-gql-queries...

**Comment by cl-homu** [comment]
:sunny: Test successful - [checks-core](https://github.com/smartcontractkit/chainlink/runs/4143795551?check_suite_focus=true), [checks-lint](https://github.com/smartcontractkit/chainlink/runs/4143714230?check_suite_focus=true), [checks-npm](https://github.com/smartcontractkit/chainlink/runs/4143884536?check_suite_focus=true), [checks-operator](https://github.com/smartcontractkit/chainlink/runs/4143714222?check_suite_focus=true), [checks-prettier](https://github.com/smartcontractkit/chainlink/runs/4143714316?check_suite_focus=true), [checks-solidity](https://github.com/smartcontractkit/chainlink/runs/4143714314?check_suite_focus=true)
Approved by: jmank88
Pushing f67741ec133a2689221f998d33565107306806e2 to feature/sc-20876/nodes-gql-queries...

**Comment by cl-homu** [comment]
:sunny: Test successful - [checks-core](https://github.com/smartcontractkit/chainlink/runs/4143818416?check_suite_focus=true), [checks-lint](https://github.com/smartcontractkit/chainlink/runs/4143714230?check_suite_focus=true), [checks-npm](https://github.com/smartcontractkit/chainlink/runs/4143884536?check_suite_focus=true), [checks-operator](https://github.com/smartcontractkit/chainlink/runs/4143714222?check_suite_focus=true), [checks-prettier](https://github.com/smartcontractkit/chainlink/runs/4143714316?check_suite_focus=true), [checks-solidity](https://github.com/smartcontractkit/chainlink/runs/4143714314?check_suite_focus=true)
Approved by: jmank88
Pushing f67741ec133a2689221f998d33565107306806e2 to feature/sc-20876/nodes-gql-queries...

**Comment by cl-homu** [comment]
:sunny: Test successful - [checks-core](https://github.com/smartcontractkit/chainlink/runs/4143819814?check_suite_focus=true), [checks-lint](https://github.com/smartcontractkit/chainlink/runs/4143714230?check_suite_focus=true), [checks-npm](https://github.com/smartcontractkit/chainlink/runs/4143884536?check_suite_focus=true), [checks-operator](https://github.com/smartcontractkit/chainlink/runs/4143714222?check_suite_focus=true), [checks-prettier](https://github.com/smartcontractkit/chainlink/runs/4143714316?check_suite_focus=true), [checks-solidity](https://github.com/smartcontractkit/chainlink/runs/4143714314?check_suite_focus=true)
Approved by: jmank88
Pushing f67741ec133a2689221f998d33565107306806e2 to feature/sc-20876/nodes-gql-queries...

**Comment by cl-homu** [comment]
:sunny: Test successful - [checks-core](https://github.com/smartcontractkit/chainlink/runs/4143819814?check_suite_focus=true), [checks-lint](https://github.com/smartcontractkit/chainlink/runs/4143714230?check_suite_focus=true), [checks-npm](https://github.com/smartcontractkit/chainlink/runs/4143901667?check_suite_focus=true), [checks-operator](https://github.com/smartcontractkit/chainlink/runs/4143714222?check_suite_focus=true), [checks-prettier](https://github.com/smartcontractkit/chainlink/runs/4143714316?check_suite_focus=true), [checks-solidity](https://github.com/smartcontractkit/chainlink/runs/4143714314?check_suite_focus=true)
Approved by: jmank88
Pushing f67741ec133a2689221f998d33565107306806e2 to feature/sc-20876/nodes-gql-queries...

**Comment by cl-homu** [comment]
:eyes: Test was successful, but fast-forwarding failed: 422 Update is not a fast forward

**Comment by cl-homu** [comment]
:sunny: Test successful - [checks-core](https://github.com/smartcontractkit/chainlink/runs/4143859708?check_suite_focus=true), [checks-lint](https://github.com/smartcontractkit/chainlink/runs/4143714230?check_suite_focus=true), [checks-npm](https://github.com/smartcontractkit/chainlink/runs/4143923670?check_suite_focus=true), [checks-operator](https://github.com/smartcontractkit/chainlink/runs/4143714222?check_suite_focus=true), [checks-prettier](https://github.com/smartcontractkit/chainlink/runs/4143714316?check_suite_focus=true), [checks-solidity](https://github.com/smartcontractkit/chainlink/runs/4143714314?check_suite_focus=true)
Approved by: jmank88
Pushing f67741ec133a2689221f998d33565107306806e2 to feature/sc-20876/nodes-gql-queries...

**Comment by cl-homu** [comment]
:eyes: Test was successful, but fast-forwarding failed: 422 Update is not a fast forward

**Comment by cl-homu** [comment]
:sunny: Test successful - [checks-core](https://github.com/smartcontractkit/chainlink/runs/4143884454?check_suite_focus=true), [checks-lint](https://github.com/smartcontractkit/chainlink/runs/4143714230?check_suite_focus=true), [checks-npm](https://github.com/smartcontractkit/chainlink/runs/4143923670?check_suite_focus=true), [checks-operator](https://github.com/smartcontractkit/chainlink/runs/4143714222?check_suite_focus=true), [checks-prettier](https://github.com/smartcontractkit/chainlink/runs/4143714316?check_suite_focus=true), [checks-solidity](https://github.com/smartcontractkit/chainlink/runs/4143714314?check_suite_focus=true)
Approved by: jmank88
Pushing f67741ec133a2689221f998d33565107306806e2 to feature/sc-20876/nodes-gql-queries...

**Comment by cl-homu** [comment]
:eyes: Test was successful, but fast-forwarding failed: 422 Update is not a fast forward

**Comment by cl-homu** [comment]
:sunny: Test successful - [checks-core](https://github.com/smartcontractkit/chainlink/runs/4143923716?check_suite_focus=true), [checks-lint](https://github.com/smartcontractkit/chainlink/runs/4143714230?check_suite_focus=true), [checks-npm](https://github.com/smartcontractkit/chainlink/runs/4143923670?check_suite_focus=true), [checks-operator](https://github.com/smartcontractkit/chainlink/runs/4143714222?check_suite_focus=true), [checks-prettier](https://github.com/smartcontractkit/chainlink/runs/4143714316?check_suite_focus=true), [checks-solidity](https://github.com/smartcontractkit/chainlink/runs/4143714314?check_suite_focus=true)
Approved by: jmank88
Pushing f67741ec133a2689221f998d33565107306806e2 to feature/sc-20876/nodes-gql-queries...

**Comment by cl-homu** [comment]
:eyes: Test was successful, but fast-forwarding failed: 422 Update is not a fast forward

**Comment by cl-homu** [comment]
:sunny: Test successful - [checks-core](https://github.com/smartcontractkit/chainlink/runs/4143916306?check_suite_focus=true), [checks-lint](https://github.com/smartcontractkit/chainlink/runs/4143714230?check_suite_focus=true), [checks-npm](https://github.com/smartcontractkit/chainlink/runs/4143923670?check_suite_focus=true), [checks-operator](https://github.com/smartcontractkit/chainlink/runs/4143714222?check_suite_focus=true), [checks-prettier](https://github.com/smartcontractkit/chainlink/runs/4143714316?check_suite_focus=true), [checks-solidity](https://github.com/smartcontractkit/chainlink/runs/4143714314?check_suite_focus=true)
Approved by: jmank88
Pushing f67741ec133a2689221f998d33565107306806e2 to feature/sc-20876/nodes-gql-queries...

**Comment by cl-homu** [comment]
:eyes: Test was successful, but fast-forwarding failed: 422 Update is not a fast forward

**Comment by cl-homu** [comment]
:umbrella: The latest upstream changes made this pull request unmergeable. Please [resolve the merge conflicts](https://rustc-dev-guide.rust-lang.org/git.html#rebasing-and-conflicts).

**Comment by cl-homu** [comment]
:warning: The base branch changed to `develop`, and the PR will need to be re-approved.

**Pull request closed without merging**
