### PR TITLE
Cron  & Web V2 Support Added to Operator UI

### PR DESCRIPTION
**Pull request by AndrewInsignares**
Operator UI Support for Cron and Web V2 Jobs

- add web job from toml spec
- run web job from "Run" button on Jobs page 
- add cron job from toml spec 

Screenshots of Successful & Failed Pipeline Runs Jobs View: 

Screen Shot 2021-04-20 at 3 40 47 AM

Screen Shot 2021-04-20 at 3 42 57 AM

Screen Shot 2021-04-20 at 3 43 05 AM

Web Error Flow:
https://user-images.githubusercontent.com/3578730/116729110-c76dc780-a9b4-11eb-86cb-8213bec0a25a.mov

Web success flow:
https://user-images.githubusercontent.com/3578730/116729145-d2c0f300-a9b4-11eb-9326-bff320f9b083.mov

### CODE REVIEW

**Comment by AndrewInsignares** [comment]
@jkongie what's the proper way to address the linting here? Are you running a linter locally before pushing?

**Comment by jkongie** [comment]
> @jkongie what's the proper way to address the linting here? Are you running a linter locally before pushing?

I'm running prettier on save as I have it hooked up in my VSCode, but you could just run the linter itself if you prefer

**Comment by AndrewInsignares** [comment]
> > @jkongie what's the proper way to address the linting here? Are you running a linter locally before pushing?
> 
> I'm running prettier on save as I have it hooked up in my VSCode, but you could just run the linter itself if you prefer

Roger, setting it up to run locally~

**Review by jkongie — DISMISSED** [review]
LGTM

**Review by jkongie — APPROVED** [review]

**Pull request merged**
