### PR TITLE
Golint: check for missing / badly formatted GoDocs

### PR DESCRIPTION
**Pull request by Nic0S**
- Change golint to only alert on new issues
- Enable GoDoc comment formatting checks

### CODE REVIEW

**Comment by archseer** [comment]
Isn't this a duplicate of https://github.com/smartcontractkit/chainlink/blob/develop/.github/workflows/golangci-lint.yml ?

**Comment by Nic0S** [comment]
Yup good point, missed that. Neither one seems to be catching any issues as far as I can tell..will try to figure out why

**Comment by archseer** [comment]
The linter does work, or at least it used to last time I tweaked it. We use it to catch a whole bunch of common bugs: https://github.com/smartcontractkit/chainlink/blob/develop/.golangci.yml#L32-L75

**Comment by Nic0S** [comment]
Yup this is working, looks like comment linting is disabled by default. I'm trying to figure out if it's possible to enable "comment should be of the form" GoDoc lints only on new linting issues

**Review by se3000 — APPROVED** [review]

**Pull request merged**
