### PR TITLE
Replace gorm with sqlx in transaction controller test

### PR DESCRIPTION
**Pull request by RensR**

### CODE REVIEW

**Review by pinebit — DISMISSED** [review]

**Comment by RensR** [comment]
@cl-homu r+

**Comment by cl-homu** [comment]
@RensR: :key: Insufficient privileges: Not in reviewers

**Comment by RensR** [comment]
@cl-homu r+

**Comment by cl-homu** [comment]
@RensR: :key: Insufficient privileges: Not in reviewers

**Comment by samsondav** [comment]
@cl-homu r+

**Comment by cl-homu** [comment]
:pushpin: Commit f5d3d8753a1971e5cd0dcc1d306e3da9ce729589 has been approved by `samsondav`

**Comment by cl-homu** [comment]
:hourglass: Testing commit f5d3d8753a1971e5cd0dcc1d306e3da9ce729589 with merge 4be2ca22344b7971a3554de32c5f5868b9301f3d...

**Comment by cl-homu** [comment]
:broken_heart: Test failed - [checks-core](https://github.com/smartcontractkit/chainlink/runs/4165679665?check_suite_focus=true)

**Comment by archseer** [comment]
@cl-homu retry

**Comment by cl-homu** [comment]
:hourglass: Testing commit f5d3d8753a1971e5cd0dcc1d306e3da9ce729589 with merge c2df4c548580035cc3fb64d71afc329686f19ec5...

**Comment by cl-homu** [comment]
:broken_heart: Test failed - [checks-core](https://github.com/smartcontractkit/chainlink/runs/4168138815?check_suite_focus=true)

**Comment by cl-homu** [comment]
:umbrella: The latest upstream changes (presumably #5420) made this pull request unmergeable. Please [resolve the merge conflicts](https://rustc-dev-guide.rust-lang.org/git.html#rebasing-and-conflicts).

**Pull request closed without merging**
