### PR TITLE
[TT-1194] do not set programmatically finality tag

### PR DESCRIPTION
**Pull request by Tofel**

### CODE REVIEW

**Review by AnieeG — APPROVED** [review]
why do you consider it wrong? If you don't have this handling your test will expect certain finality behavior based on network config and chainlink node will behave with a different behavior. Also if you want a specific Finality Depth the logic honor that. 
You can set `evmConfig.Chain.FinalityDepth` and `evmConfig.Chain.FinalityTagEnabled `from chainlink toml and the corresponding nil checks will be false

**Review by AnieeG — CHANGES_REQUESTED** [review]
Commented above.

**Comment by iljapavlovs** [comment]
> why do you consider it wrong? If you don't have this handling your test will expect certain finality behavior based on network config and chainlink node will behave with a different behavior. Also if you want a specific Finality Depth the logic honor that. You can set `evmConfig.Chain.FinalityDepth` and `evmConfig.Chain.FinalityTagEnabled `from chainlink toml and the corresponding nil checks will be false

@AnieeG in VRF for example, we are not setting `FinalityTagEnabled` and hence, it is disabled by default as it is the default value for it. So now I just want to be sure that we have the same env in smoke tests as in PROD, so it should be directly set from the toml config

**Review by iljapavlovs — APPROVED** [review]

**Comment by AnieeG** [comment]
> > why do you consider it wrong? If you don't have this handling your test will expect certain finality behavior based on network config and chainlink node will behave with a different behavior. Also if you want a specific Finality Depth the logic honor that. You can set `evmConfig.Chain.FinalityDepth` and `evmConfig.Chain.FinalityTagEnabled `from chainlink toml and the corresponding nil checks will be false
> 
> @AnieeG in VRF for example, we are not setting `FinalityTagEnabled` and hence, it is disabled by default as it is the default value for it. So now I just want to be sure that we have the same env in smoke tests as in PROD, so it should be directly set from the toml config

you should either change network config  in test config for that or change CommonChainConfig in chainlink toml. Omitting this is not a good idea for tests using finality tag - https://github.com/smartcontractkit/chainlink-testing-framework/blob/main/config/node.go#L5

**Comment by iljapavlovs** [comment]
> you should either change network config in test config for that or change CommonChainConfig in chainlink toml. Omitting this is not a good idea for tests using finality tag

@AnieeG but here we are replicating the same scenario as if this would be infra-k8s for PROD. So if the default value in chainlink core will change, then great - we gonna also test that. So I mean we need to be sure that our test env has the same setup as the PROD env. In Prod env we are not automagically setting `FinalityTagEnabled`

Again - this is configurable - your test's idea of finality and chainlink node's idea of finality should match.

**Review by AnieeG — APPROVED** [review]

**Review by lukaszcl — APPROVED** [review]

**Pull request merged**
