### PR TITLE
Add requestTimeout support on FluxMonitor jobs

### PR DESCRIPTION
**Pull request by RyanRHall**
Addresses [#169737200](https://www.pivotaltracker.com/story/show/169737200)

### CODE REVIEW

**Comment by thodges-gh** [comment]
I would have really preferred this to be an environment config for the node operator. Using this as a job param gives control to Carol, for something that she doesn't _actually_ know what the value should be, but Neil would. For example, Neil's job reaches out to an external adapter that actually makes several calls, taking 12 seconds, but Ned's job only needs to make one quick call, taking 1 second. If Carol defines a low requestTimeout of 3 seconds, that would be fine with Ned, but would harm Neil. This control needs to fallback to the node operator to determine the correct value.

**Comment by RyanRHall** [comment]
hmmm that's a really good point @thodges-gh 

I think the idea behind putting this in the job spec was that it may be advantageous to make timeouts configurable by job because some endpoints may require significantly more time to return a response.

If, for example, someone created a job that has to talk to an endpoint that does some on the fly NLP and takes ~15 seconds to respond. We don't want to force every other job to wait that long before timing out since most responses should complete within a second or two.

Any thoughts on how to remedy this?

**Comment by thodges-gh** [comment]
I think the best way to handle this is to add the requestTimeout as a param when creating/editing the bridge, otherwise use a global environment config for http endpoints (including the HttpGet and HttpPost adapters). This way, the value is still configurable for Neil, since multiple jobs using the same bridge would still need the same timeout, but it's hidden from Carol, preventing the possibility of abuse.

**Comment by RyanRHall** [comment]
@thodges-gh that's a great idea. The bridge definitely makes sense to me as the right place place for this.

**Comment by RyanRHall** [comment]
Closing in favor of https://github.com/smartcontractkit/chainlink/pull/2570

**Comment by RyanRHall** [comment]
Added a story to create the `requestTimeout` param on bridges [here](https://www.pivotaltracker.com/story/show/171987763).

**Pull request closed without merging**
