### PR TITLE
Update circleci's postgres image to 11.5

### PR DESCRIPTION
**Pull request by HenryNguyen5**

### CODE REVIEW

**Comment by HenryNguyen5** [comment]
@felder-cl still failing here for circleci

**Comment by felder-cl** [comment]
Any reason why you weren't using circleci's Postgres 11.5 image?

**Comment by HenryNguyen5** [comment]
@felder-cl this was me reproducing the bug filed in: https://www.pivotaltracker.com/story/show/169991336
We want to migrate off of circleci images since they dont reproduce what we would use in production, also we should not have test failures by switching between two images for postgres, this indicates a bug somewhere

**Comment by felder-cl** [comment]
Its working for circleci's Postgres 11.5 image, so its probably a configuration issue between circleci's Postgres image, and the default one.

**Pull request merged**
