### PR TITLE
Remove gorm from keeper, directrequest

### PR DESCRIPTION
**Pull request by samsondav**

### CODE REVIEW

**Review by jmank88 — APPROVED** [review]

**Review by pinebit — APPROVED** [review]

**Comment by pinebit** [comment]
@cl-homu r+

**Comment by cl-homu** [comment]
:pushpin: Commit 624c7e18176a17b5c240b85363a608ccf7d4ad12 has been approved by `pinebit`

**Comment by cl-homu** [comment]
:hourglass: Testing commit 624c7e18176a17b5c240b85363a608ccf7d4ad12 with merge 354ee77ef47daf5f971fc88db25ffd0a38c7da43...

**Comment by cl-homu** [comment]
:broken_heart: Test failed - [checks-core](https://github.com/smartcontractkit/chainlink/runs/4178042734?check_suite_focus=true)

**Comment by jmank88** [comment]
@cl-homu retry

**Comment by cl-homu** [comment]
:hourglass: Testing commit 624c7e18176a17b5c240b85363a608ccf7d4ad12 with merge 9cc6787ae21643a0124e7f547ed116bfe6fbc286...

**Comment by cl-homu** [comment]
:broken_heart: Test failed - [checks-core](https://github.com/smartcontractkit/chainlink/runs/4178220215?check_suite_focus=true)

**Comment by jmank88** [comment]
@cl-homu retry
:fairy:

**Comment by cl-homu** [comment]
:hourglass: Testing commit 624c7e18176a17b5c240b85363a608ccf7d4ad12 with merge 35b0924583ba3ca80e288b2b42876e4f1f5a30dd...

**Comment by cl-homu** [comment]
:sunny: Test successful - [checks-core](https://github.com/smartcontractkit/chainlink/runs/4178397680?check_suite_focus=true), [checks-lint](https://github.com/smartcontractkit/chainlink/runs/4178397740?check_suite_focus=true), [checks-npm](https://github.com/smartcontractkit/chainlink/runs/4178397880?check_suite_focus=true), [checks-operator](https://github.com/smartcontractkit/chainlink/runs/4178397675?check_suite_focus=true), [checks-prettier](https://github.com/smartcontractkit/chainlink/runs/4178397911?check_suite_focus=true), [checks-solidity](https://github.com/smartcontractkit/chainlink/runs/4178397814?check_suite_focus=true)
Approved by: pinebit
Pushing 35b0924583ba3ca80e288b2b42876e4f1f5a30dd to develop...

**Pull request merged**
