### PR TITLE
[NONEVM-876] Pass DataSource to Solana relay

### PR DESCRIPTION
**Pull request by reductionista**
JIRA: [NONEVM-876](https://smartcontract-it.atlassian.net/browse/NONEVM-876)

### Requires
- https://github.com/smartcontractkit/chainlink-solana/pull/916

[NONEVM-876]: https://smartcontract-it.atlassian.net/browse/NONEVM-876?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

### CODE REVIEW

**Comment by reductionista** [comment]
Looks like the failing test is due to `TxRetention` being added in this commit to `chainlink-solana`, but no corresponding commit updating the test for it in `chainlink` repo yet:
https://github.com/smartcontractkit/chainlink-solana/commit/65ae13752669cfe8786512e180c690815d6d9ec6

@amit-momin are there plans to update `chainlink` unit tests for this?

**Comment by amit-momin** [comment]
> Looks like the failing test is due to `TxRetention` being added in this commit to `chainlink-solana`, but no corresponding commit updating the test for it in `chainlink` repo yet: [smartcontractkit/chainlink-solana@65ae137](https://github.com/smartcontractkit/chainlink-solana/commit/65ae13752669cfe8786512e180c690815d6d9ec6)
> 
> @amit-momin are there plans to update `chainlink` unit tests for this?

Hey @reductionista, I have this [PR](https://github.com/smartcontractkit/chainlink/pull/15104) open to update `chainlink`. Sorry for the inconvenience. The solana change went in late today so planning to get this reviewed and merged tomorrow.

**Review by jmank88 — DISMISSED** [review]

**Review by dhaidashenko — DISMISSED** [review]

**Comment by reductionista** [comment]
@jmank88 Looks like Solana Build Test Image is failing due to `GOTOOLCHAIN=local` again?
```
go: go.mod requires go >= 1.23 (running go 1.22.9; GOTOOLCHAIN=local)
```
I think you had a fix for this, do we need to apply it here?

**Comment by jmank88** [comment]
> @jmank88 Looks like Solana Build Test Image is failing due to `GOTOOLCHAIN=local` again?
> 
> ```
> go: go.mod requires go >= 1.23 (running go 1.22.9; GOTOOLCHAIN=local)
> ```
> 
> I think you had a fix for this, do we need to apply it here?

I updated all the core references to 1.23, so this must be coming from Solana
Edit: nix is on `go_1_23` already :thinking:

**Comment by reductionista** [comment]
> I updated all the core references to 1.23, so this must be coming from Solana
> Edit: nix is on go_1_23 already 🤔

I tried that, as well as setting `GOTOOLCHAIN=auto` in the environment for the Solana Build Test Image step in this repo. The first one I don't think was relevant at all, since none of the CI files from that repo get run as far as I can tell. Setting it here almost worked, it at least shows `GOTOOLCHAIN=auto` as in the environment when you expand the build step.  Unfortunately, that's only outside of the docker image which is built with this script:

https://github.com/smartcontractkit/chainlink-solana/blob/develop/integration-tests/scripts/buildTestImage

(same method is used for building the chainlink/integration-tests here...)
https://github.com/smartcontractkit/chainlink/blob/develop/integration-tests/scripts/buildTestImage

So I think the problem might be with the base image named `test-base-image` it references from the docker file while building the smoke tests? I'm guessing this is built by QA from some repo of theirs, but I'm not sure where--maybe they need to update a docker file of theirs?  Or maybe adding an ENV GOTOOLCHAIN=auto env var to the dockerfile it uses would work?
https://github.com/smartcontractkit/chainlink-solana/blob/develop/integration-tests/test.Dockerfile

@kalverra 

UPDATE: looks like `test-base-image` is built from `chainlink-testing-framework`, which apparently was just updated to go 1.23 10 hours ago! So I probably just need to update the `go.mod` in chainlink-solana to the latest version of `chainlink-testing-framework`, trying that now

**Review by aalu1418 — APPROVED** [review]

**Review by ilija42 — APPROVED** [review]

**Pull request merged**
