### PR TITLE
Add Gzip compression

### PR DESCRIPTION
**Pull request by rupurt**
Without Gzip = 713KB

without-gzip

With Gzip = 194KB

with-gzip

### CODE REVIEW

**Comment by dimroc** [comment]
This seems to be failing because the `/v2/backup` endpoint doesn't like being gzipped. The `gin/gzip` documentation says to exclude things from middleware, like gzip, by using groups. Unfortunately, our `v2` group has many things we would still like gzipped.

Another option could be to wrap the `gzip` middleware with our own `funcHandler` to exclude the `/backup` path.

They have a method `shouldCompress` that illustrates how they skip certain files based on extensions since they're already gzipped:

```golang
func shouldCompress(req *http.Request) bool {
        ...
	extension := filepath.Ext(req.URL.Path)

	switch extension {
	case ".png", ".gif", ".jpeg", ".jpg":
		return false
	default:
		return true
	}
}
```

https://github.com/gin-contrib/gzip/blob/master/gzip.go#L83-L84

**Comment by j16r** [comment]
Didn't the security review suggest we turn off compression because it's an effective DoS?

**Comment by se3000** [comment]
@j16r that concern is around what we accept, not what we send.

**Comment by rupurt** [comment]
@dimroc sweet. Thanks for looking into that and coming up with some approaches. I like the idea of using `.nogzip`. It provides a nice and easy way to compare the size savings.

**Comment by rupurt** [comment]
@j16r had the idea of doing it during build time. There is decent support for it:

- https://github.com/webpack-contrib/compression-webpack-plugin
- https://github.com/mynameiswhm/brotli-webpack-plugin

**Comment by rupurt** [comment]
Closing in favor of new stories:

- https://www.pivotaltracker.com/story/show/159078220
- https://www.pivotaltracker.com/story/show/159078405

**Pull request closed without merging**
