### PR TITLE
format explorer dates as 'YYYY-MM-DD h:mm:ss A'

### PR DESCRIPTION
**Pull request by dimroc**

### CODE REVIEW

**Comment by NavyAdmiral** [comment]
https://github.com/you-dont-need/You-Dont-Need-Momentjs#format
Isn't momentjs too big to be used only for this?

**Comment by dimroc** [comment]
I have no qualms adding 16kb to our minified javascript. I would rather that than maintain more of our own code. 

In the link you posted:
> However, if you are working on a performance sensitive web application, it might cause a huge performance overhead because of its complex APIs and large bundle size.

The client is not a performance sensitive web application so I'm inclined to leave it as is. If others feel differently, let me know.

**Comment by dimroc** [comment]
Just to clear up a discrepancy. There are two sizes quoted:

image

**Comment by rupurt** [comment]
I'm fine with moment. If we need to optimize to this level of performance we can at a later date. 

Fwiw we also serve all external packages in the production build from https://unpkg.com/

https://github.com/smartcontractkit/chainlink/blob/master/explorer/client/package.json#L50

**Pull request merged**
