### PR TITLE
FIX: `increaseTime5Minutes` to increase by 5 instead of 50

### PR DESCRIPTION
**Pull request by alexroan**

### CODE REVIEW

**Review by samsondav — COMMENTED** [review]
Good grief 🤦‍♂️ 😁

**Comment by samsondav** [comment]
@cl-homu r+

**Comment by cl-homu** [comment]
:pushpin: Commit 8b3fa72c3e5346494423393e31ff8d4e9ebb8925 has been approved by `samsondav`

**Comment by cl-homu** [comment]
:sunny: Test successful - [checks-core](https://github.com/smartcontractkit/chainlink/runs/4239298468?check_suite_focus=true), [checks-lint](https://github.com/smartcontractkit/chainlink/runs/4239298351?check_suite_focus=true), [checks-npm](https://github.com/smartcontractkit/chainlink/runs/4239298772?check_suite_focus=true), [checks-operator](https://github.com/smartcontractkit/chainlink/runs/4239298463?check_suite_focus=true), [checks-prettier](https://github.com/smartcontractkit/chainlink/runs/4239298743?check_suite_focus=true), [checks-solidity](https://github.com/smartcontractkit/chainlink/runs/4239298426?check_suite_focus=true)
Approved by: samsondav
Pushing f3c26cdcdd6b11b0099769598ae9bba0be1cd2ac to develop...

**Pull request merged**
