### PR TITLE
chore: remove gorm from transaction controller

### PR DESCRIPTION
**Pull request by RensR**
fixed the ordering of the preloaded tx attempts

### CODE REVIEW

**Review by pinebit — APPROVED** [review]

**Comment by pinebit** [comment]
@cl-homu r+

**Comment by cl-homu** [comment]
:pushpin: Commit 5fdb87130b9d5d1cf87b31c6fe6ae273adde40f4 has been approved by `pinebit`

**Comment by cl-homu** [comment]
:hourglass: Testing commit 5fdb87130b9d5d1cf87b31c6fe6ae273adde40f4 with merge b87aa63145f32108bc467dcb8cc7b30087169fda...

**Comment by cl-homu** [comment]
:sunny: Test successful - [checks-core](https://github.com/smartcontractkit/chainlink/runs/4192177644?check_suite_focus=true), [checks-lint](https://github.com/smartcontractkit/chainlink/runs/4192177649?check_suite_focus=true), [checks-npm](https://github.com/smartcontractkit/chainlink/runs/4192177765?check_suite_focus=true), [checks-operator](https://github.com/smartcontractkit/chainlink/runs/4192177841?check_suite_focus=true), [checks-prettier](https://github.com/smartcontractkit/chainlink/runs/4192177834?check_suite_focus=true), [checks-solidity](https://github.com/smartcontractkit/chainlink/runs/4192177646?check_suite_focus=true)
Approved by: pinebit
Pushing b87aa63145f32108bc467dcb8cc7b30087169fda to develop...

**Pull request merged**
