### PR TITLE
weaken nodejs requirement to 10.6

### PR DESCRIPTION
**Pull request by felder-cl**
Improve support by relaxing the nodejs requirement to the minor version.

### CODE REVIEW

**Comment by rupurt** [comment]
@HenryNguyen5 if we use `^` the minor version can get out of sync. How do you feel about using `~` which will use the patch version?

e.g. `~10.16.3`

**Comment by HenryNguyen5** [comment]
Works for me

**Comment by felder-cl** [comment]
"I think we should have this requirement in all sub-packages, along with the root workspace"

I've updated all the necessary packages which reference node as a dependency.

**Comment by felder-cl** [comment]
Maybe extending the requirement will be best in another PR?  I personally don't have an opinion about whether its better or worse however.

**Comment by rupurt** [comment]
@felder-cl 👍 to a separate PR for the other packages

**Pull request merged**
