### PR TITLE
SonarQube in CI/CD

### PR DESCRIPTION
**Pull request by chainchad**
In future PR's:
- The unit tests in $OUTPUT_FILE will need to be changed to output to json. Sonar can only read JSON output from `go test -json ...`. 
- golangci-lint's GitHub action will need to be sorted out so that it can output like `github-actions,checkstyle:report.json` (right now it's hardcoded to `github-actions`) as well as moved to the `ci-core` workflow so Sonar can ingest.

### CODE REVIEW

**Comment by jmank88** [comment]
Oh, do we have to choose between coverage and golangci-lint since they are separate workflows?

**Comment by chainchad** [comment]
@jmank88 I'd like to get both coverage and lint reports in there. I need to confirm if we can run this action multiple times safely (one for lint, one for coverage+tests) or if it has to be ran one time with all of those files included.

**Comment by chainchad** [comment]
Also, getting lint is going to be fun due to the golangci-lint action being hardcoded to only use the `github-actions` output format even though the underlying golangci-lint config supports multiple output formats (would like to do `github-actions,checkstyle:report.json` or similar).

**Review by chudilka1 — APPROVED** [review]
Though we are blocked from populating the eslint-, golint-, and test reports, we still may proceed with the SonarQube analysis results (some language-related rules, as well as coverage, etc). Even missing some reports, the results will be profitable. 
For now, we will consider the absence of some artifacts as non-blocking issues. To let the Foundations team provide feedback as soon as the SQ trial license ends, it is necessary to get them unblocked to start receiving analysis results in their feature branches.

The tasks to add all missing metrics in the future are created:
    - https://smartcontract-it.atlassian.net/browse/RE-164 (integrate ESLint report to SonarQube)
    - https://smartcontract-it.atlassian.net/browse/RE-165 (integrate Golinters report to SonarQube)
    - https://smartcontract-it.atlassian.net/browse/RE-166 (integrate go test report to SonarQube)

**Pull request merged**
