### PR TITLE
Create Dependabot config file

### PR DESCRIPTION
**Pull request by naveensrinivasan**
Enable dependabot for managing dependencies

image

https://github.com/naveensrinivasan/chainlink/pulls

### CODE REVIEW

**Comment by se3000** [comment]
Hi Naveen, thanks for the PR. We actually already run Dependabot, but we manage the config through the Github UI. What benefit do you see any benefit to adding the config into the repo?

**Comment by naveensrinivasan** [comment]
> Hi Naveen, thanks for the PR. We actually already run Dependabot, but we manage the config through the Github UI. What benefit do you see any benefit to adding the config into the repo?

Hi Steve, I see this is a monorepo with lots of dependencies with different languages like go, typescript, docker, etc. 
I am wasn't sure it was all configured with dependabot UI. Here is an example of what could be configured https://github.com/ossf/scorecard/blob/main/.github/dependabot.yml

On the specifics of what the config provides versus UI. Here are the options https://dependabot.com/docs/config-file/#available-configuration-options , AFAIK some of these options aren't available in UI.

**Comment by naveensrinivasan** [comment]
One of the options I think that can be configured with the config 
**is only allow security updates**

```
version: 1
update_configs:
  - package_manager: "javascript"
    directory: "/"
    update_schedule: "daily"
    allowed_updates:
      - match:
          update_type: "security"
      - match:
          dependency_name: "lodash"
```          
For some dependencies, the project might not want to upgrade every release and would want for only security fixes.

**Comment by se3000** [comment]
Closing this, because someone copied our existing off-chain config to a file since you opened it.

Really appreciate the PRs @naveensrinivasan. Thanks for thanks for all the help with CI, we're always trying to improve our the automated security tooling.

**Pull request closed without merging**
