### PR TITLE
Balance precision and hover

### PR DESCRIPTION
**Pull request by NavyAdmiral**
I didn't style the hover, because from what I've gleaned this is only a temporary design. I don't like the variable names too much, open for suggestions.

### CODE REVIEW

**Comment by NavyAdmiral** [comment]
@dimroc Can you rerun the workflow for me? The tests should be green from the current commits.
image

**Comment by dimroc** [comment]
It still failed @NavyAdmiral

**Comment by NavyAdmiral** [comment]
@dimroc I'll push again. For some reason circleci doesn't see the latest commit from this PR:
image

The code in this PR is different.

**Comment by NavyAdmiral** [comment]
@dimroc 🥗

**Pull request merged**
