### PR TITLE
@chainlink/contracts new major version branch

### PR DESCRIPTION
**Pull request by alexroan**
This is a long-lived branch containing a number of breaking changes to the @chainlink/contracts package. Currently implemented (applied to v0.8 contracts and above):

* Alter interface contract naming scheme from `ExampleInterface.sol` to `IExample.sol`

### CODE REVIEW

**Review by makramkd — DISMISSED** [review]
VRF-related changes LGTM 👍

**Review by infiloop2 — DISMISSED** [review]
keepers changes lgtm 👍

**Review by se3000 — CHANGES_REQUESTED** [review]
This is going to break our current contract package layout, necessitating a major version bump. Given that we have more breaking changes in mind, I think we should hold these back and release them all at once. Merging them onto develop isn't really an option because that will block any other releases we want to make before all breaking changes are in. I see two options for how to proceed:
1. Create a separate branch that all the breaking changes live on and regularly rebase it on top of develop until all changes are in.
2.  Make aliases of the new names that match the old names, so that the old package names continue working with the new names. Something like
`interface AggregatorV3Interface is IAggregatorV3 {};`

I prefer 2 because branches are a pain. It would be easy to cleanup `*Interface.sol` when we're ready to make the switch, and we can start pushing the new pattern internally before then. We may have to use option 1 in the future, but keeping as much on `develop` as possible would be ideal.

**Comment by alexroan** [comment]
Closing this based on conversations with @se3000 and @HenryNguyen5

**Pull request closed without merging**
