### PR TITLE
[merged] gorm removal under services/job

### PR DESCRIPTION
**Pull request by pinebit**
This is another bit of "gorm removal" work

### CODE REVIEW

**Review by samsondav — APPROVED** [review]

**Comment by samsondav** [comment]
@cl-homu r+

**Comment by cl-homu** [comment]
:pushpin: Commit ef1883b3253ba462b7b851d9d6a2f27320e98a0b has been approved by `samsondav`

**Comment by cl-homu** [comment]
:hourglass: Testing commit ef1883b3253ba462b7b851d9d6a2f27320e98a0b with merge 9e838ce7adb3d1aaf1f36fb54f4e761f2578c897...

**Comment by cl-homu** [comment]
:sunny: Test successful - [checks-core](https://github.com/smartcontractkit/chainlink/runs/4167672119?check_suite_focus=true), [checks-lint](https://github.com/smartcontractkit/chainlink/runs/4167672314?check_suite_focus=true), [checks-npm](https://github.com/smartcontractkit/chainlink/runs/4167672460?check_suite_focus=true), [checks-operator](https://github.com/smartcontractkit/chainlink/runs/4167672122?check_suite_focus=true), [checks-prettier](https://github.com/smartcontractkit/chainlink/runs/4167672478?check_suite_focus=true), [checks-solidity](https://github.com/smartcontractkit/chainlink/runs/4167672288?check_suite_focus=true)
Approved by: samsondav
Pushing 9e838ce7adb3d1aaf1f36fb54f4e761f2578c897 to develop...

**Pull request closed without merging**
