### PR TITLE
Remove gorm from offchainreporting and eventbroadcaster

### PR DESCRIPTION
**Pull request by samsondav**

### CODE REVIEW

**Review by pinebit — APPROVED** [review]

**Review by j16r — APPROVED** [review]

**Comment by j16r** [comment]
@cl-homu r+

**Comment by cl-homu** [comment]
:pushpin: Commit f83a58136d798da7a23d85f453cdb9268021421e has been approved by `j16r`

**Comment by cl-homu** [comment]
:hourglass: Testing commit f83a58136d798da7a23d85f453cdb9268021421e with merge 4b999463466d896e8432f59a98df462170c60337...

**Comment by cl-homu** [comment]
:sunny: Test successful - [checks-core](https://github.com/smartcontractkit/chainlink/runs/4176948591?check_suite_focus=true), [checks-lint](https://github.com/smartcontractkit/chainlink/runs/4176948392?check_suite_focus=true), [checks-npm](https://github.com/smartcontractkit/chainlink/runs/4176948643?check_suite_focus=true), [checks-operator](https://github.com/smartcontractkit/chainlink/runs/4176948390?check_suite_focus=true), [checks-prettier](https://github.com/smartcontractkit/chainlink/runs/4176948569?check_suite_focus=true), [checks-solidity](https://github.com/smartcontractkit/chainlink/runs/4176948450?check_suite_focus=true)
Approved by: j16r
Pushing 4b999463466d896e8432f59a98df462170c60337 to develop...

**Pull request merged**
