### PR TITLE
update readme with required binaries to generate mocks and run make abigen

### PR DESCRIPTION
**Pull request by whatsadebugger**
I found myself needing these binaries to be able to run go generate and make abigen

### CODE REVIEW

**Comment by whatsadebugger** [comment]
> LGTM

Do you know if i have to make any changes for the changelog

**Comment by samsondav** [comment]
@whatsadebugger nope, looks fine.

**Comment by samsondav** [comment]
@whatsadebugger needs rebasing

**Comment by whatsadebugger** [comment]
Any way to see the failures on circle ci @samsondav

**Comment by whatsadebugger** [comment]
image
Is it possible for you to rerun these or should i just rebase

**Comment by samsondav** [comment]
@whatsadebugger I think we had a broken CI for a while in develop branch, would you mind rebasing again please?

**Comment by whatsadebugger** [comment]
> @whatsadebugger I think we had a broken CI for a while in develop branch, would you mind rebasing again please?

looks like its still giving me an issue after rebase

**Comment by se3000** [comment]
There is some permissions issues with some of the builds. I've moved your PR [over here](https://github.com/smartcontractkit/chainlink/pull/3140) and should have it merged soon.

**Pull request closed without merging**
