### PR TITLE
shorten module name from github.com/smartcontractkit/chainlink -> chainlink

### PR DESCRIPTION
**Pull request by whatsadebugger**

### CODE REVIEW

**Comment by whatsadebugger** [comment]
working through different build errors slowly getting there

**Comment by j16r** [comment]
Closing this in favor of @whatsadebugger's work.

**Comment by whatsadebugger** [comment]
> Closing this in favor of @whatsadebugger's work.

this is my branch though lol

**Comment by j16r** [comment]
Actually remind re-opening this noe @whatsadebugger ? If I reopen it, it changes ownership to me and I can no longer review.

**Comment by whatsadebugger** [comment]
sure

**Pull request closed without merging**
