### PR TITLE
bump deps

### PR DESCRIPTION
**Pull request by jmank88**
- https://github.com/fxamacker/cbor/v2 v2.5.0

- https://github.com/go-webauthn/webauthn v0.8.6

- https://github.com/prometheus/common v0.45.0

- https://github.com/prometheus/prometheus v0.47.2

- https://github.com/tidwall/gjson v1.17.0

- https://gonum.org/v1/gonum v0.14.0

### CODE REVIEW

**Comment by jmank88** [comment]
@nolag it looks like this cbor version bump is breaking some tests :facepalm:

**Comment by fxamacker** [comment]
> @nolag it looks like this cbor version bump is breaking some tests 🤦

Hi, I'm the maintainer of the [cbor library](https://github.com/fxamacker/cbor).  I'm sorry the update to v2.5.0 broke some tests, maybe I can help.

cbor library changes are usually introduced as non-default options to prevent compatibility breaks but some exceptions were made in v2.5 and highlighted in [⭐ Notable Changes to Review Before Upgrading](https://github.com/fxamacker/cbor/releases/tag/v2.5.0) in v2.5.0 release notes.

For example, test breakage might be due to improved error-handling in cbor v2.5.0 (e.g. previously missed problem being detected and reported as error).

A small self-contained reproducer could help projects upgrade to v2.5.0 (e.g. https://github.com/go-webauthn/webauthn v0.8.6 listed in this pull request is also using cbor v2.4.0).  I can take a look at the reproducer this weekend if one is available.

Please let me know if I can help in any other way to make the upgrade work.

**Comment by jmank88** [comment]
It looks like we just had 3 test cases failing due to:
> Make Unmarshal() and Valid() return cbor.ExtraneousDataError (instead of ignoring extraneous data if any remain).

Two were just incidental bytes to truncate, and one was an explicit trailing bytes case that needed to change its expectation of success.

**Review by nolag — DISMISSED** [review]
Thanks, I'll verify what will need to be done in the branch I'm working on and make it work there or work with the cbor dev :).

**Review by nolag — COMMENTED** [review]
I have more context now, we can't just update it.  The encoding sent from EVM will have the extra trailing characters.  We would need to use the length in the array returned (the first word) to trim the cbor before calling the function.  

I'm going to downgrade cbor's use to 2.4 the branch that we're using for our work so we don't need to tackle it now, but we (or the functions team) should try to eventually fix this so it can be upgraded.

**Comment by fxamacker** [comment]
> I have more context now, we can't just update it. The encoding sent from EVM will have the extra trailing characters. We would need to use the length in the array returned (the first word) to trim the cbor before calling the function.
> 
> I'm going to downgrade cbor's use to 2.4 the branch that we're using for our work so we don't need to tackle it now, but we (or the functions team) should try to eventually fix this so it can be upgraded.

@nolag `UnmarshalFirst()` function added in v2.5.0 can be used to detect and handle extraneous bytes without error.

```Go
// UnmarshalFirst decodes first CBOR data item and returns remaining bytes.
rest, err = cbor.UnmarshalFirst(b, &v)   // decode []byte b to v
```

**Review by samsondav — APPROVED** [review]

**Review by nolag — APPROVED** [review]

**Review by CL-Andrew — APPROVED** [review]

**Pull request merged**
