### PR TITLE
Prevent accidental 'npm install' commands 

### PR DESCRIPTION
**Pull request by AbGuthrie**
The repo is configured to use yarn as the package manager, so this PR adds a safeguard.

Running the `npm install` in the root of the repo, or in any folder that has a package.json will be halted.

This is important because this repo has only the yarn.lock file at the root, but does not have a package.lock. 
yarn `workspaces` is defined, so the nested package.json files respect the root yarn.lock

Because there is no package-lock.json, an accidental `npm install` could could possibly download a compromised/malicious updated version of packages which could also contain a nefarious post install script.

Attempting to run `npm install` will result in the following:

image

Also commit update to yarn.lock changes (remove axios and simplify follow-redirects)

### CODE REVIEW

**Review by jmank88 — APPROVED** [review]

**Review by RyanRHall — CHANGES_REQUESTED** [review]
what if we just gitignore `package-lock.json`? Will that do the job?

It looks like yarn still supports [preinstall](https://yarnpkg.com/advanced/lifecycle-scripts)

**Comment by AbGuthrie** [comment]
> what if we just gitignore `package-lock.json`? Will that do the job?

Hi Ryan, the idea is to protect anyone working with repo (or CI/CD), from accidentally running `npm install` in general. 

The worry is that because there is no package-lock.json committed into the repo, npm will fetch and (potentially run post install scripts) any new (maybe malicious) versions of all packages listed. 

It's better to prevent this from happening, and rely on safeguards in the yarn.lock file 

Devs can still add/update dependencies with `yarn add mypackage`

**Review by RyanRHall — APPROVED** [review]

**Comment by samsondav** [comment]
How can the changelog checker be failing ?! Makes no sense.

**Comment by jmank88** [comment]
> How can the changelog checker be failing ?! Makes no sense.

Did it just fail to post? 
```
Warning: Unexpected input(s) 'check_for_duplicate_msg', valid inputs are ['entryPoint', 'args', 'msg']
Run unsplash/comment-on-pr@d1a1d5dd1eb1bb657a01f4d92dd5e4d5bb7857d3
  with:
    msg: I see that you haven't updated any CHANGELOG files. Would it make sense to do so?
    check_for_duplicate_msg: false
  env:
    GITHUB_TOKEN: ***
```

**Comment by jmank88** [comment]
Oh there is a real error below that warning:
```
POST https://api.github.com/repos/smartcontractkit/chainlink/issues/5050/comments: 403 - Resource not accessible by integration
```

**Comment by AbGuthrie** [comment]
This was reviewed here, but merged via an internal branch here https://github.com/smartcontractkit/chainlink/pull/5176

**Pull request closed without merging**
