### PR TITLE
fix starting node without eth connection

### PR DESCRIPTION
**Pull request by se3000**

### CODE REVIEW

**Review by j16r — APPROVED** [review]

**Review by thodges-gh — APPROVED** [review]
Acceptance :+1:

**Review by samsondav — APPROVED** [review]

**Comment by samsondav** [comment]
Out of interest why would you want to boot the node without ethereum?

**Comment by topliceanu** [comment]
The ticket suggests this is needed because some integration tests are failing.
I'd be curious to see what kind of integration tests don't use Geth at all?

**Comment by se3000** [comment]
@samsondav @topliceanu We have a repo for a generalized [external initiator to listen for requests from other chains](https://github.com/smartcontractkit/external-initiator) and there is an integration test in there that is failing.

**Pull request merged**
