### PR TITLE
Expunge gorm entirely

### PR DESCRIPTION
**Pull request by samsondav**
Final PR to remove gorm completely.

It leaves `gorm.io/datatypes` since this is relatively simple. It might be removed in a subsequent PR.

### CODE REVIEW

**Review by jmank88 — DISMISSED** [review]

**Comment by jmank88** [comment]
@cl-homu r+

**Comment by cl-homu** [comment]
:pushpin: Commit 32f3baf8545e31fe307b6eb5fee5539bd338031d has been approved by `jmank88`

**Comment by cl-homu** [comment]
:hourglass: Testing commit 32f3baf8545e31fe307b6eb5fee5539bd338031d with merge ef359f97ae24fc4012fac37f20f4fe8b35d9f42c...

**Comment by samsondav** [comment]
@cl-homu r+

**Comment by cl-homu** [comment]
:pushpin: Commit 92268dc11dcbc922bdb695ece82b93da3a8395bd has been approved by `samsondav`

**Comment by cl-homu** [comment]
:hourglass: Testing commit 92268dc11dcbc922bdb695ece82b93da3a8395bd with merge 5888510d2fdeea6a115bd0c47afedd7793e749e4...

**Comment by cl-homu** [comment]
:sunny: Test successful - [checks-core](https://github.com/smartcontractkit/chainlink/runs/4217028655?check_suite_focus=true), [checks-lint](https://github.com/smartcontractkit/chainlink/runs/4217028456?check_suite_focus=true), [checks-npm](https://github.com/smartcontractkit/chainlink/runs/4217028508?check_suite_focus=true), [checks-operator](https://github.com/smartcontractkit/chainlink/runs/4217028459?check_suite_focus=true), [checks-prettier](https://github.com/smartcontractkit/chainlink/runs/4217028662?check_suite_focus=true), [checks-solidity](https://github.com/smartcontractkit/chainlink/runs/4217028653?check_suite_focus=true)
Approved by: samsondav
Pushing 5888510d2fdeea6a115bd0c47afedd7793e749e4 to develop...

**Pull request merged**
