### PR TITLE
go 1.18; gonum 0.11.0; golangci-lint 1.45.2

### PR DESCRIPTION
**Pull request by jmank88**
- `go 1.18`

and minimal requirements:
- `gonum.org/v1/gonum v0.11.0`
- `golangci-lint v1.45.2`

### CODE REVIEW

**Review by pinebit — DISMISSED** [review]
Cool!

**Review by makramkd — DISMISSED** [review]
:shipit:

**Review by pinebit — APPROVED** [review]

**Review by samsondav — DISMISSED** [review]
Yes

**Comment by jmank88** [comment]
Open for review - @CL-Andrew any reservations about this?

**Comment by jmank88** [comment]
Not a blocker, but mockery does not 'just work': https://github.com/vektra/mockery/issues/434
Work around is to use a parallel `go1.17.x` install for generation.

**Review by CL-Andrew — APPROVED** [review]
Thanks @jmank88 LGTM

**Pull request merged**
