### PR TITLE
Use shorter module name

### PR DESCRIPTION
**Pull request by j16r**
This doesn't really change much / fix anything, though may help `goimports` resolve a little better if you're working with a fork (I am ;) ).

It's just a personal preference, I like the shorter imports.

### CODE REVIEW

**Comment by se3000** [comment]
Looks similar to https://github.com/smartcontractkit/chainlink/pull/1742. @whatsadebugger any reason you closed it?

**Comment by whatsadebugger** [comment]
I wasn't sure if the feedback given was for or against the change

**Comment by j16r** [comment]
@whatsadebugger as you can see, I am all for it ;) Will approve yours if you post it back up.

**Comment by whatsadebugger** [comment]
> @whatsadebugger as you can see, I am all for it ;) Will approve yours if you post it back up.

Sure i'll have it ready soon

**Comment by j16r** [comment]
Closing this in favor of https://github.com/smartcontractkit/chainlink/pull/1870

**Pull request closed without merging**
