### PR TITLE
Use info level for successful explorer websocket connections

### PR DESCRIPTION
**Pull request by rupurt**
- Add warn log for duplicate connections
- Change unsuccessful connections log levels to warn

### CODE REVIEW

**Comment by j16r** [comment]
One thing to caution is that the logs here will be very noisy on a production server, since worms/hackers etc. will repeatedly be attempting to connect to the port. So something to watch out for.

**Comment by rupurt** [comment]
This shouldn't add any extra noise. The failure attempts were already logging with `info` and I've switched them to `warn`.

This PR will add a new `info` log entry for successful connections though.

**Comment by rupurt** [comment]
@j16r do you think `warn` is suitable for the failed connections? It was already logging as `info` so there won't be any new entries.

We will have a few more log entries now for successful connections, but that will help with debugging issues in production.

**Comment by j16r** [comment]
Yeah I think it's fine, I've just found myself sometimes running production servers at level WARN because they were so noisy and logging was affecting performance, shouldn't be an issue for us though.

**Pull request merged**
