### PR TITLE
[merged] Remove auto update in favor of Homu

### PR DESCRIPTION
**Pull request by j16r**
Hoping to get Homu to merge this one.

### CODE REVIEW

**Review by samsondav — DISMISSED** [review]

**Comment by j16r** [comment]
@cl-homu r+

**Comment by cl-homu** [comment]
:pushpin: Commit 004fc74882968c1299ea7f35da3f34d16d924c3e has been approved by `j16r`

**Comment by cl-homu** [comment]
:hourglass: Testing commit 004fc74882968c1299ea7f35da3f34d16d924c3e with merge 8051761308ab112034a5e853c7d804767b975996...

**Comment by j16r** [comment]
@cl-homu r+

**Comment by cl-homu** [comment]
:pushpin: Commit 0c28a048589022599a543dc589758b7c3d1bd00f has been approved by `j16r`

**Comment by cl-homu** [comment]
:hourglass: Testing commit 0c28a048589022599a543dc589758b7c3d1bd00f with merge 7e0c1ae9834757ea5d72ef4c7b23937c3e6a97b9...

**Comment by cl-homu** [comment]
:sunny: Test successful - [checks-core](https://github.com/smartcontractkit/chainlink/runs/4075303208?check_suite_focus=true), [checks-lint](https://github.com/smartcontractkit/chainlink/runs/4075303284?check_suite_focus=true), [checks-npm](https://github.com/smartcontractkit/chainlink/runs/4075303337?check_suite_focus=true), [checks-operator](https://github.com/smartcontractkit/chainlink/runs/4075303202?check_suite_focus=true), [checks-prettier](https://github.com/smartcontractkit/chainlink/runs/4075303356?check_suite_focus=true), [checks-solidity](https://github.com/smartcontractkit/chainlink/runs/4075303217?check_suite_focus=true)
Approved by: j16r
Pushing 7e0c1ae9834757ea5d72ef4c7b23937c3e6a97b9 to develop...

**Comment by cl-homu** [comment]
:eyes: Test was successful, but fast-forwarding failed: 422 At least 1 approving review is required by reviewers with write access.

**Review by archseer — APPROVED** [review]

**Comment by j16r** [comment]
@homu retry

**Comment by j16r** [comment]
@cl-homu retry

**Comment by cl-homu** [comment]
:hourglass: Testing commit 0c28a048589022599a543dc589758b7c3d1bd00f with merge deb770712a446718f87dce46eefc4c4277e93140...

**Comment by cl-homu** [comment]
:broken_heart: Test failed - [checks-core](https://github.com/smartcontractkit/chainlink/runs/4075515543?check_suite_focus=true)

**Comment by j16r** [comment]
@cl-homu retry

**Comment by cl-homu** [comment]
:hourglass: Testing commit 0c28a048589022599a543dc589758b7c3d1bd00f with merge 4e24c9639d3e4fe6403add2a6522bc082232c6ff...

**Comment by cl-homu** [comment]
:sunny: Test successful - [checks-core](https://github.com/smartcontractkit/chainlink/runs/4075580185?check_suite_focus=true), [checks-lint](https://github.com/smartcontractkit/chainlink/runs/4075580116?check_suite_focus=true), [checks-npm](https://github.com/smartcontractkit/chainlink/runs/4075580223?check_suite_focus=true), [checks-operator](https://github.com/smartcontractkit/chainlink/runs/4075580114?check_suite_focus=true), [checks-prettier](https://github.com/smartcontractkit/chainlink/runs/4075580209?check_suite_focus=true), [checks-solidity](https://github.com/smartcontractkit/chainlink/runs/4075580138?check_suite_focus=true)
Approved by: j16r
Pushing 4e24c9639d3e4fe6403add2a6522bc082232c6ff to develop...

**Comment by cl-homu** [comment]
:eyes: Test was successful, but fast-forwarding failed: 422 At least 1 approving review is required by reviewers with write access.

**Comment by archseer** [comment]
@cl-homu retry

**Comment by cl-homu** [comment]
:hourglass: Testing commit 0c28a048589022599a543dc589758b7c3d1bd00f with merge ad68a40e62dce8a2650dbcf9f7aea0515f3fdbaa...

**Comment by cl-homu** [comment]
:sunny: Test successful - [checks-core](https://github.com/smartcontractkit/chainlink/runs/4076030799?check_suite_focus=true), [checks-lint](https://github.com/smartcontractkit/chainlink/runs/4076030749?check_suite_focus=true), [checks-npm](https://github.com/smartcontractkit/chainlink/runs/4076030752?check_suite_focus=true), [checks-operator](https://github.com/smartcontractkit/chainlink/runs/4076030693?check_suite_focus=true), [checks-prettier](https://github.com/smartcontractkit/chainlink/runs/4076030785?check_suite_focus=true), [checks-solidity](https://github.com/smartcontractkit/chainlink/runs/4076030751?check_suite_focus=true)
Approved by: j16r
Pushing ad68a40e62dce8a2650dbcf9f7aea0515f3fdbaa to develop...

**Comment by cl-homu** [comment]
:eyes: Test was successful, but fast-forwarding failed: 422 At least 1 approving review is required by reviewers with write access.

**Review by archseer — APPROVED** [review]

**Comment by j16r** [comment]
@cl-homu r+

**Comment by cl-homu** [comment]
:pushpin: Commit 9882f2cca5ae4bff4e890b583079d3502d1ae49a has been approved by `j16r`

**Comment by cl-homu** [comment]
:hourglass: Testing commit 9882f2cca5ae4bff4e890b583079d3502d1ae49a with merge 2bdf2a7eed13b6ee236e3dc081fc62fcf1aa0584...

**Comment by cl-homu** [comment]
:sunny: Test successful - [checks-core](https://github.com/smartcontractkit/chainlink/runs/4118706572?check_suite_focus=true), [checks-lint](https://github.com/smartcontractkit/chainlink/runs/4118706027?check_suite_focus=true), [checks-npm](https://github.com/smartcontractkit/chainlink/runs/4118706281?check_suite_focus=true), [checks-operator](https://github.com/smartcontractkit/chainlink/runs/4118706023?check_suite_focus=true), [checks-prettier](https://github.com/smartcontractkit/chainlink/runs/4118706526?check_suite_focus=true), [checks-solidity](https://github.com/smartcontractkit/chainlink/runs/4118706326?check_suite_focus=true)
Approved by: j16r
Pushing 2bdf2a7eed13b6ee236e3dc081fc62fcf1aa0584 to develop...

**Comment by cl-homu** [comment]
:eyes: Test was successful, but fast-forwarding failed: 422 At least 1 approving review is required by reviewers with write access.

**Comment by j16r** [comment]
@cl-homu r+

**Comment by cl-homu** [comment]
:bulb: This pull request was already approved, no need to approve it again.

- This pull request previously failed. You should add more commits to fix the bug, or use `retry` to trigger a build again.

**Comment by cl-homu** [comment]
:pushpin: Commit 9882f2cca5ae4bff4e890b583079d3502d1ae49a has been approved by `j16r`

**Comment by j16r** [comment]
@cl-homu retry

**Comment by j16r** [comment]
@cl-homu r-

**Comment by j16r** [comment]
@cl-homu r-

**Comment by j16r** [comment]
@cl-homu retry

**Comment by j16r** [comment]
@cl-homu retry

**Comment by j16r** [comment]
@cl-homu r-

**Comment by j16r** [comment]
@cl-homu r+

**Comment by cl-homu** [comment]
:pushpin: Commit 9882f2cca5ae4bff4e890b583079d3502d1ae49a has been approved by `j16r`

**Comment by cl-homu** [comment]
:hourglass: Testing commit 9882f2cca5ae4bff4e890b583079d3502d1ae49a with merge 4cc5397120d5632e9b6e8d8dea74a5fa0a603f38...

**Comment by cl-homu** [comment]
:broken_heart: Test failed - [checks-core](https://github.com/smartcontractkit/chainlink/runs/4123503168?check_suite_focus=true)

**Comment by cl-homu** [comment]
:sunny: Test successful - [checks-core](https://github.com/smartcontractkit/chainlink/runs/4123549269?check_suite_focus=true), [checks-lint](https://github.com/smartcontractkit/chainlink/runs/4123503220?check_suite_focus=true), [checks-npm](https://github.com/smartcontractkit/chainlink/runs/4123549256?check_suite_focus=true), [checks-operator](https://github.com/smartcontractkit/chainlink/runs/4123503216?check_suite_focus=true), [checks-prettier](https://github.com/smartcontractkit/chainlink/runs/4123503254?check_suite_focus=true), [checks-solidity](https://github.com/smartcontractkit/chainlink/runs/4123503162?check_suite_focus=true)
Approved by: j16r
Pushing 4cc5397120d5632e9b6e8d8dea74a5fa0a603f38 to develop...

**Comment by cl-homu** [comment]
:eyes: Test was successful, but fast-forwarding failed: 422 At least 1 approving review is required by reviewers with write access.

**Comment by j16r** [comment]
@cl-homu retry

**Comment by cl-homu** [comment]
:hourglass: Testing commit 9882f2cca5ae4bff4e890b583079d3502d1ae49a with merge 7b24e72e661cebf0d42ec7b1c64315b26c4bfeda...

**Comment by cl-homu** [comment]
:sunny: Test successful - [checks-core](https://github.com/smartcontractkit/chainlink/runs/4123610873?check_suite_focus=true), [checks-lint](https://github.com/smartcontractkit/chainlink/runs/4123610759?check_suite_focus=true), [checks-npm](https://github.com/smartcontractkit/chainlink/runs/4123610838?check_suite_focus=true), [checks-operator](https://github.com/smartcontractkit/chainlink/runs/4123610780?check_suite_focus=true), [checks-prettier](https://github.com/smartcontractkit/chainlink/runs/4123610870?check_suite_focus=true), [checks-solidity](https://github.com/smartcontractkit/chainlink/runs/4123610821?check_suite_focus=true)
Approved by: j16r
Pushing 7b24e72e661cebf0d42ec7b1c64315b26c4bfeda to develop...

**Pull request closed without merging**
