### PR TITLE
Add test for ClobberNodesFromENV

### PR DESCRIPTION
**Pull request by samsondav**

### CODE REVIEW

**Review by jmank88 — APPROVED** [review]

**Comment by jmank88** [comment]
@cl-homu r+

**Comment by cl-homu** [comment]
:pushpin: Commit 11ef966a2e53a79a6c8783cf1c84f99e21b12261 has been approved by `jmank88`

**Comment by cl-homu** [comment]
:hourglass: Testing commit 11ef966a2e53a79a6c8783cf1c84f99e21b12261 with merge a8b68c4215ee66f24c6444e0fc69cba5d760e861...

**Comment by cl-homu** [comment]
:broken_heart: Test failed - [checks-core](https://github.com/smartcontractkit/chainlink/runs/4177871304?check_suite_focus=true)

**Comment by jmank88** [comment]
@cl-homu retry

**Comment by cl-homu** [comment]
:hourglass: Testing commit 11ef966a2e53a79a6c8783cf1c84f99e21b12261 with merge 7bb11398c17abebd8596e0776931232e0d8c067e...

**Comment by cl-homu** [comment]
:broken_heart: Test failed - [checks-core](https://github.com/smartcontractkit/chainlink/runs/4178126225?check_suite_focus=true)

**Comment by jmank88** [comment]
@cl-homu retry
:magic_wand:

**Comment by cl-homu** [comment]
:hourglass: Testing commit 11ef966a2e53a79a6c8783cf1c84f99e21b12261 with merge 1da065c41e40bab5ef6e3f93cb7653f2e582ab1b...

**Comment by cl-homu** [comment]
:sunny: Test successful - [checks-core](https://github.com/smartcontractkit/chainlink/runs/4178312011?check_suite_focus=true), [checks-lint](https://github.com/smartcontractkit/chainlink/runs/4178311754?check_suite_focus=true), [checks-npm](https://github.com/smartcontractkit/chainlink/runs/4178311748?check_suite_focus=true), [checks-operator](https://github.com/smartcontractkit/chainlink/runs/4178311816?check_suite_focus=true), [checks-prettier](https://github.com/smartcontractkit/chainlink/runs/4178312081?check_suite_focus=true), [checks-solidity](https://github.com/smartcontractkit/chainlink/runs/4178312010?check_suite_focus=true)
Approved by: jmank88
Pushing 1da065c41e40bab5ef6e3f93cb7653f2e582ab1b to develop...

**Pull request merged**
