### PR TITLE
Revamp TaskExpansionPanel

### PR DESCRIPTION
**Pull request by NavyAdmiral**
Old
image
New
image

@rupurt PTAL whenever

### CODE REVIEW

**Comment by NavyAdmiral** [comment]
@rupurt should be done, I have no idea what made the tests fail though

**Comment by rupurt** [comment]
@NavyAdmiral enzyme doesn't like sibling fragments so I'd say it's `renderParams`

**Comment by NavyAdmiral** [comment]
> @NavyAdmiral enzyme doesn't like sibling fragments so I'd say it's `renderParams`

good call but unfortunately it's no that :(
sadly my local setup doesnt allow me to test, fetch-mock is still broken for me. 
I'll try to figure out what's wrong

**Comment by NavyAdmiral** [comment]
@rupurt I finally resolved it! I can't describe how I'd like optional chaining to become available.

**Pull request merged**
