### PR TITLE
[OCR2 - Relay Solana] Add smartcontractkit/chainlink-solana module

### PR DESCRIPTION
**Pull request by krebernisak**

### CODE REVIEW

**Comment by cl-homu** [comment]
:umbrella: The latest upstream changes (presumably 02677d29d620baf6c036851f6a491572b328201b) made this pull request unmergeable. Please [resolve the merge conflicts](https://rustc-dev-guide.rust-lang.org/git.html#rebasing-and-conflicts).

**Comment by cl-homu** [comment]
:umbrella: The latest upstream changes (presumably a151fa2d4204c0ce6f63b16faa92505cbb535203) made this pull request unmergeable. Please [resolve the merge conflicts](https://rustc-dev-guide.rust-lang.org/git.html#rebasing-and-conflicts).

**Comment by cl-homu** [comment]
:umbrella: The latest upstream changes (presumably cdee680327978f7b26f1ec6d6e00d86b72a9e528) made this pull request unmergeable. Please [resolve the merge conflicts](https://rustc-dev-guide.rust-lang.org/git.html#rebasing-and-conflicts).

**Review by aalu1418 — APPROVED** [review]
This looks good to merged into `feature/relay`

I think future updates to the solana lib can be made as additional PRs/changes

**Pull request merged**
